// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.19.6
// source: pci.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pci_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_pci_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_pci_proto_rawDescGZIP(), []int{0}
}

type OkResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok      bool   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *OkResponse) Reset() {
	*x = OkResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pci_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OkResponse) ProtoMessage() {}

func (x *OkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pci_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OkResponse.ProtoReflect.Descriptor instead.
func (*OkResponse) Descriptor() ([]byte, []int) {
	return file_pci_proto_rawDescGZIP(), []int{1}
}

func (x *OkResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *OkResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type VmNameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VmName string `protobuf:"bytes,1,opt,name=vm_name,json=vmName,proto3" json:"vm_name,omitempty"`
}

func (x *VmNameRequest) Reset() {
	*x = VmNameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pci_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VmNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VmNameRequest) ProtoMessage() {}

func (x *VmNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pci_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VmNameRequest.ProtoReflect.Descriptor instead.
func (*VmNameRequest) Descriptor() ([]byte, []int) {
	return file_pci_proto_rawDescGZIP(), []int{2}
}

func (x *VmNameRequest) GetVmName() string {
	if x != nil {
		return x.VmName
	}
	return ""
}

type GPUReferenceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GpuRef string `protobuf:"bytes,1,opt,name=gpu_ref,json=gpuRef,proto3" json:"gpu_ref,omitempty"`
}

func (x *GPUReferenceRequest) Reset() {
	*x = GPUReferenceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pci_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GPUReferenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPUReferenceRequest) ProtoMessage() {}

func (x *GPUReferenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pci_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPUReferenceRequest.ProtoReflect.Descriptor instead.
func (*GPUReferenceRequest) Descriptor() ([]byte, []int) {
	return file_pci_proto_rawDescGZIP(), []int{3}
}

func (x *GPUReferenceRequest) GetGpuRef() string {
	if x != nil {
		return x.GpuRef
	}
	return ""
}

type VMGPURequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VmName string `protobuf:"bytes,1,opt,name=vm_name,json=vmName,proto3" json:"vm_name,omitempty"`
	GpuRef string `protobuf:"bytes,2,opt,name=gpu_ref,json=gpuRef,proto3" json:"gpu_ref,omitempty"`
}

func (x *VMGPURequest) Reset() {
	*x = VMGPURequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pci_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VMGPURequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VMGPURequest) ProtoMessage() {}

func (x *VMGPURequest) ProtoReflect() protoreflect.Message {
	mi := &file_pci_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VMGPURequest.ProtoReflect.Descriptor instead.
func (*VMGPURequest) Descriptor() ([]byte, []int) {
	return file_pci_proto_rawDescGZIP(), []int{4}
}

func (x *VMGPURequest) GetVmName() string {
	if x != nil {
		return x.VmName
	}
	return ""
}

func (x *VMGPURequest) GetGpuRef() string {
	if x != nil {
		return x.GpuRef
	}
	return ""
}

type HostGPU struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeName      string   `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Path          string   `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Address       string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Domain        uint32   `protobuf:"varint,4,opt,name=domain,proto3" json:"domain,omitempty"`
	Bus           uint32   `protobuf:"varint,5,opt,name=bus,proto3" json:"bus,omitempty"`
	Slot          uint32   `protobuf:"varint,6,opt,name=slot,proto3" json:"slot,omitempty"`
	Function      uint32   `protobuf:"varint,7,opt,name=function,proto3" json:"function,omitempty"`
	Driver        string   `protobuf:"bytes,8,opt,name=driver,proto3" json:"driver,omitempty"`
	Vendor        string   `protobuf:"bytes,9,opt,name=vendor,proto3" json:"vendor,omitempty"`
	VendorId      string   `protobuf:"bytes,10,opt,name=vendor_id,json=vendorId,proto3" json:"vendor_id,omitempty"`
	Product       string   `protobuf:"bytes,11,opt,name=product,proto3" json:"product,omitempty"`
	ProductId     string   `protobuf:"bytes,12,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Class         string   `protobuf:"bytes,13,opt,name=class,proto3" json:"class,omitempty"`
	IommuGroup    int32    `protobuf:"varint,14,opt,name=iommu_group,json=iommuGroup,proto3" json:"iommu_group,omitempty"`
	NumaNode      int32    `protobuf:"varint,15,opt,name=numa_node,json=numaNode,proto3" json:"numa_node,omitempty"`
	ManagedByVfio bool     `protobuf:"varint,16,opt,name=managed_by_vfio,json=managedByVfio,proto3" json:"managed_by_vfio,omitempty"`
	AttachedToVms []string `protobuf:"bytes,17,rep,name=attached_to_vms,json=attachedToVms,proto3" json:"attached_to_vms,omitempty"`
}

func (x *HostGPU) Reset() {
	*x = HostGPU{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pci_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostGPU) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostGPU) ProtoMessage() {}

func (x *HostGPU) ProtoReflect() protoreflect.Message {
	mi := &file_pci_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostGPU.ProtoReflect.Descriptor instead.
func (*HostGPU) Descriptor() ([]byte, []int) {
	return file_pci_proto_rawDescGZIP(), []int{5}
}

func (x *HostGPU) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *HostGPU) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *HostGPU) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *HostGPU) GetDomain() uint32 {
	if x != nil {
		return x.Domain
	}
	return 0
}

func (x *HostGPU) GetBus() uint32 {
	if x != nil {
		return x.Bus
	}
	return 0
}

func (x *HostGPU) GetSlot() uint32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *HostGPU) GetFunction() uint32 {
	if x != nil {
		return x.Function
	}
	return 0
}

func (x *HostGPU) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *HostGPU) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *HostGPU) GetVendorId() string {
	if x != nil {
		return x.VendorId
	}
	return ""
}

func (x *HostGPU) GetProduct() string {
	if x != nil {
		return x.Product
	}
	return ""
}

func (x *HostGPU) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *HostGPU) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

func (x *HostGPU) GetIommuGroup() int32 {
	if x != nil {
		return x.IommuGroup
	}
	return 0
}

func (x *HostGPU) GetNumaNode() int32 {
	if x != nil {
		return x.NumaNode
	}
	return 0
}

func (x *HostGPU) GetManagedByVfio() bool {
	if x != nil {
		return x.ManagedByVfio
	}
	return false
}

func (x *HostGPU) GetAttachedToVms() []string {
	if x != nil {
		return x.AttachedToVms
	}
	return nil
}

type VMGPU struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address  string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Domain   uint32 `protobuf:"varint,2,opt,name=domain,proto3" json:"domain,omitempty"`
	Bus      uint32 `protobuf:"varint,3,opt,name=bus,proto3" json:"bus,omitempty"`
	Slot     uint32 `protobuf:"varint,4,opt,name=slot,proto3" json:"slot,omitempty"`
	Function uint32 `protobuf:"varint,5,opt,name=function,proto3" json:"function,omitempty"`
	Managed  bool   `protobuf:"varint,6,opt,name=managed,proto3" json:"managed,omitempty"`
	Alias    string `protobuf:"bytes,7,opt,name=alias,proto3" json:"alias,omitempty"`
}

func (x *VMGPU) Reset() {
	*x = VMGPU{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pci_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VMGPU) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VMGPU) ProtoMessage() {}

func (x *VMGPU) ProtoReflect() protoreflect.Message {
	mi := &file_pci_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VMGPU.ProtoReflect.Descriptor instead.
func (*VMGPU) Descriptor() ([]byte, []int) {
	return file_pci_proto_rawDescGZIP(), []int{6}
}

func (x *VMGPU) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *VMGPU) GetDomain() uint32 {
	if x != nil {
		return x.Domain
	}
	return 0
}

func (x *VMGPU) GetBus() uint32 {
	if x != nil {
		return x.Bus
	}
	return 0
}

func (x *VMGPU) GetSlot() uint32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *VMGPU) GetFunction() uint32 {
	if x != nil {
		return x.Function
	}
	return 0
}

func (x *VMGPU) GetManaged() bool {
	if x != nil {
		return x.Managed
	}
	return false
}

func (x *VMGPU) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

type HostGPUList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gpus []*HostGPU `protobuf:"bytes,1,rep,name=gpus,proto3" json:"gpus,omitempty"`
}

func (x *HostGPUList) Reset() {
	*x = HostGPUList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pci_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostGPUList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostGPUList) ProtoMessage() {}

func (x *HostGPUList) ProtoReflect() protoreflect.Message {
	mi := &file_pci_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostGPUList.ProtoReflect.Descriptor instead.
func (*HostGPUList) Descriptor() ([]byte, []int) {
	return file_pci_proto_rawDescGZIP(), []int{7}
}

func (x *HostGPUList) GetGpus() []*HostGPU {
	if x != nil {
		return x.Gpus
	}
	return nil
}

type VMGPUList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gpus []*VMGPU `protobuf:"bytes,1,rep,name=gpus,proto3" json:"gpus,omitempty"`
}

func (x *VMGPUList) Reset() {
	*x = VMGPUList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pci_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VMGPUList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VMGPUList) ProtoMessage() {}

func (x *VMGPUList) ProtoReflect() protoreflect.Message {
	mi := &file_pci_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VMGPUList.ProtoReflect.Descriptor instead.
func (*VMGPUList) Descriptor() ([]byte, []int) {
	return file_pci_proto_rawDescGZIP(), []int{8}
}

func (x *VMGPUList) GetGpus() []*VMGPU {
	if x != nil {
		return x.Gpus
	}
	return nil
}

var File_pci_proto protoreflect.FileDescriptor

var file_pci_proto_rawDesc = []byte{
	0x0a, 0x09, 0x70, 0x63, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x70, 0x63, 0x69,
	0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x36, 0x0a, 0x0a, 0x4f, 0x6b, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x22, 0x28, 0x0a, 0x0d, 0x56, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x76, 0x6d, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x76, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x2e, 0x0a, 0x13, 0x47,
	0x50, 0x55, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x67, 0x70, 0x75, 0x5f, 0x72, 0x65, 0x66, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x70, 0x75, 0x52, 0x65, 0x66, 0x22, 0x40, 0x0a, 0x0c, 0x56,
	0x4d, 0x47, 0x50, 0x55, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x76,
	0x6d, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x76, 0x6d,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x67, 0x70, 0x75, 0x5f, 0x72, 0x65, 0x66, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x70, 0x75, 0x52, 0x65, 0x66, 0x22, 0xd8, 0x03,
	0x0a, 0x07, 0x48, 0x6f, 0x73, 0x74, 0x47, 0x50, 0x55, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x6f, 0x64,
	0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x6f,
	0x64, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x12, 0x10, 0x0a, 0x03,
	0x62, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x62, 0x75, 0x73, 0x12, 0x12,
	0x0a, 0x04, 0x73, 0x6c, 0x6f, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x73, 0x6c,
	0x6f, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16,
	0x0a, 0x06, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x12, 0x1b,
	0x0a, 0x09, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x70,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x18, 0x0d, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x6f,
	0x6d, 0x6d, 0x75, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0a, 0x69, 0x6f, 0x6d, 0x6d, 0x75, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x1b, 0x0a, 0x09, 0x6e,
	0x75, 0x6d, 0x61, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08,
	0x6e, 0x75, 0x6d, 0x61, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x26, 0x0a, 0x0f, 0x6d, 0x61, 0x6e, 0x61,
	0x67, 0x65, 0x64, 0x5f, 0x62, 0x79, 0x5f, 0x76, 0x66, 0x69, 0x6f, 0x18, 0x10, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x0d, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x64, 0x42, 0x79, 0x56, 0x66, 0x69, 0x6f,
	0x12, 0x26, 0x0a, 0x0f, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x65, 0x64, 0x5f, 0x74, 0x6f, 0x5f,
	0x76, 0x6d, 0x73, 0x18, 0x11, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0d, 0x61, 0x74, 0x74, 0x61, 0x63,
	0x68, 0x65, 0x64, 0x54, 0x6f, 0x56, 0x6d, 0x73, 0x22, 0xab, 0x01, 0x0a, 0x05, 0x56, 0x4d, 0x47,
	0x50, 0x55, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x16, 0x0a, 0x06,
	0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x64, 0x6f,
	0x6d, 0x61, 0x69, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x62, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x03, 0x62, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6c, 0x6f, 0x74, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x73, 0x6c, 0x6f, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x75,
	0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x66, 0x75,
	0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65,
	0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x22, 0x2f, 0x0a, 0x0b, 0x48, 0x6f, 0x73, 0x74, 0x47, 0x50,
	0x55, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x04, 0x67, 0x70, 0x75, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x63, 0x69, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x47, 0x50,
	0x55, 0x52, 0x04, 0x67, 0x70, 0x75, 0x73, 0x22, 0x2b, 0x0a, 0x09, 0x56, 0x4d, 0x47, 0x50, 0x55,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x04, 0x67, 0x70, 0x75, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x63, 0x69, 0x2e, 0x56, 0x4d, 0x47, 0x50, 0x55, 0x52, 0x04,
	0x67, 0x70, 0x75, 0x73, 0x32, 0xd2, 0x02, 0x0a, 0x0f, 0x53, 0x6c, 0x61, 0x76, 0x65, 0x50, 0x43,
	0x49, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2c, 0x0a, 0x0c, 0x4c, 0x69, 0x73, 0x74,
	0x48, 0x6f, 0x73, 0x74, 0x47, 0x50, 0x55, 0x73, 0x12, 0x0a, 0x2e, 0x70, 0x63, 0x69, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x1a, 0x10, 0x2e, 0x70, 0x63, 0x69, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x47,
	0x50, 0x55, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x35, 0x0a, 0x15, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x6f,
	0x73, 0x74, 0x47, 0x50, 0x55, 0x73, 0x57, 0x69, 0x74, 0x68, 0x49, 0x4f, 0x4d, 0x4d, 0x55, 0x12,
	0x0a, 0x2e, 0x70, 0x63, 0x69, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x10, 0x2e, 0x70, 0x63,
	0x69, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x47, 0x50, 0x55, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x30, 0x0a,
	0x0a, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x4d, 0x47, 0x50, 0x55, 0x73, 0x12, 0x12, 0x2e, 0x70, 0x63,
	0x69, 0x2e, 0x56, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x0e, 0x2e, 0x70, 0x63, 0x69, 0x2e, 0x56, 0x4d, 0x47, 0x50, 0x55, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x33, 0x0a, 0x0d, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x47, 0x50, 0x55, 0x54, 0x6f, 0x56, 0x4d,
	0x12, 0x11, 0x2e, 0x70, 0x63, 0x69, 0x2e, 0x56, 0x4d, 0x47, 0x50, 0x55, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x70, 0x63, 0x69, 0x2e, 0x4f, 0x6b, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x0f, 0x44, 0x65, 0x74, 0x61, 0x63, 0x68, 0x47, 0x50,
	0x55, 0x46, 0x72, 0x6f, 0x6d, 0x56, 0x4d, 0x12, 0x11, 0x2e, 0x70, 0x63, 0x69, 0x2e, 0x56, 0x4d,
	0x47, 0x50, 0x55, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x70, 0x63, 0x69,
	0x2e, 0x4f, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3c, 0x0a, 0x0f, 0x52,
	0x65, 0x74, 0x75, 0x72, 0x6e, 0x47, 0x50, 0x55, 0x54, 0x6f, 0x48, 0x6f, 0x73, 0x74, 0x12, 0x18,
	0x2e, 0x70, 0x63, 0x69, 0x2e, 0x47, 0x50, 0x55, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x70, 0x63, 0x69, 0x2e, 0x4f,
	0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x31, 0x5a, 0x2f, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4d, 0x61, 0x72, 0x75, 0x71, 0x65, 0x73, 0x2f,
	0x35, 0x31, 0x32, 0x53, 0x76, 0x4d, 0x61, 0x6e, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x70, 0x63, 0x69, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pci_proto_rawDescOnce sync.Once
	file_pci_proto_rawDescData = file_pci_proto_rawDesc
)

func file_pci_proto_rawDescGZIP() []byte {
	file_pci_proto_rawDescOnce.Do(func() {
		file_pci_proto_rawDescData = protoimpl.X.CompressGZIP(file_pci_proto_rawDescData)
	})
	return file_pci_proto_rawDescData
}

var file_pci_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_pci_proto_goTypes = []interface{}{
	(*Empty)(nil),               // 0: pci.Empty
	(*OkResponse)(nil),          // 1: pci.OkResponse
	(*VmNameRequest)(nil),       // 2: pci.VmNameRequest
	(*GPUReferenceRequest)(nil), // 3: pci.GPUReferenceRequest
	(*VMGPURequest)(nil),        // 4: pci.VMGPURequest
	(*HostGPU)(nil),             // 5: pci.HostGPU
	(*VMGPU)(nil),               // 6: pci.VMGPU
	(*HostGPUList)(nil),         // 7: pci.HostGPUList
	(*VMGPUList)(nil),           // 8: pci.VMGPUList
}
var file_pci_proto_depIdxs = []int32{
	5, // 0: pci.HostGPUList.gpus:type_name -> pci.HostGPU
	6, // 1: pci.VMGPUList.gpus:type_name -> pci.VMGPU
	0, // 2: pci.SlavePCIService.ListHostGPUs:input_type -> pci.Empty
	0, // 3: pci.SlavePCIService.ListHostGPUsWithIOMMU:input_type -> pci.Empty
	2, // 4: pci.SlavePCIService.ListVMGPUs:input_type -> pci.VmNameRequest
	4, // 5: pci.SlavePCIService.AttachGPUToVM:input_type -> pci.VMGPURequest
	4, // 6: pci.SlavePCIService.DetachGPUFromVM:input_type -> pci.VMGPURequest
	3, // 7: pci.SlavePCIService.ReturnGPUToHost:input_type -> pci.GPUReferenceRequest
	7, // 8: pci.SlavePCIService.ListHostGPUs:output_type -> pci.HostGPUList
	7, // 9: pci.SlavePCIService.ListHostGPUsWithIOMMU:output_type -> pci.HostGPUList
	8, // 10: pci.SlavePCIService.ListVMGPUs:output_type -> pci.VMGPUList
	1, // 11: pci.SlavePCIService.AttachGPUToVM:output_type -> pci.OkResponse
	1, // 12: pci.SlavePCIService.DetachGPUFromVM:output_type -> pci.OkResponse
	1, // 13: pci.SlavePCIService.ReturnGPUToHost:output_type -> pci.OkResponse
	8, // [8:14] is the sub-list for method output_type
	2, // [2:8] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pci_proto_init() }
func file_pci_proto_init() {
	if File_pci_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pci_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pci_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OkResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pci_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VmNameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pci_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GPUReferenceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pci_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VMGPURequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pci_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostGPU); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pci_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VMGPU); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pci_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostGPUList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pci_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VMGPUList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pci_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pci_proto_goTypes,
		DependencyIndexes: file_pci_proto_depIdxs,
		MessageInfos:      file_pci_proto_msgTypes,
	}.Build()
	File_pci_proto = out.File
	file_pci_proto_rawDesc = nil
	file_pci_proto_goTypes = nil
	file_pci_proto_depIdxs = nil
}
