// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.6
// source: pci.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_pci_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_pci_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_pci_proto_rawDescGZIP(), []int{0}
}

type OkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OkResponse) Reset() {
	*x = OkResponse{}
	mi := &file_pci_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OkResponse) ProtoMessage() {}

func (x *OkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pci_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OkResponse.ProtoReflect.Descriptor instead.
func (*OkResponse) Descriptor() ([]byte, []int) {
	return file_pci_proto_rawDescGZIP(), []int{1}
}

func (x *OkResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *OkResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type VmNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmName        string                 `protobuf:"bytes,1,opt,name=vm_name,json=vmName,proto3" json:"vm_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VmNameRequest) Reset() {
	*x = VmNameRequest{}
	mi := &file_pci_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VmNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VmNameRequest) ProtoMessage() {}

func (x *VmNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pci_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VmNameRequest.ProtoReflect.Descriptor instead.
func (*VmNameRequest) Descriptor() ([]byte, []int) {
	return file_pci_proto_rawDescGZIP(), []int{2}
}

func (x *VmNameRequest) GetVmName() string {
	if x != nil {
		return x.VmName
	}
	return ""
}

type GPUReferenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GpuRef        string                 `protobuf:"bytes,1,opt,name=gpu_ref,json=gpuRef,proto3" json:"gpu_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GPUReferenceRequest) Reset() {
	*x = GPUReferenceRequest{}
	mi := &file_pci_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GPUReferenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPUReferenceRequest) ProtoMessage() {}

func (x *GPUReferenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pci_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPUReferenceRequest.ProtoReflect.Descriptor instead.
func (*GPUReferenceRequest) Descriptor() ([]byte, []int) {
	return file_pci_proto_rawDescGZIP(), []int{3}
}

func (x *GPUReferenceRequest) GetGpuRef() string {
	if x != nil {
		return x.GpuRef
	}
	return ""
}

type VMGPURequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmName        string                 `protobuf:"bytes,1,opt,name=vm_name,json=vmName,proto3" json:"vm_name,omitempty"`
	GpuRef        string                 `protobuf:"bytes,2,opt,name=gpu_ref,json=gpuRef,proto3" json:"gpu_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VMGPURequest) Reset() {
	*x = VMGPURequest{}
	mi := &file_pci_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VMGPURequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VMGPURequest) ProtoMessage() {}

func (x *VMGPURequest) ProtoReflect() protoreflect.Message {
	mi := &file_pci_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VMGPURequest.ProtoReflect.Descriptor instead.
func (*VMGPURequest) Descriptor() ([]byte, []int) {
	return file_pci_proto_rawDescGZIP(), []int{4}
}

func (x *VMGPURequest) GetVmName() string {
	if x != nil {
		return x.VmName
	}
	return ""
}

func (x *VMGPURequest) GetGpuRef() string {
	if x != nil {
		return x.GpuRef
	}
	return ""
}

type HostGPU struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeName      string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Domain        uint32                 `protobuf:"varint,4,opt,name=domain,proto3" json:"domain,omitempty"`
	Bus           uint32                 `protobuf:"varint,5,opt,name=bus,proto3" json:"bus,omitempty"`
	Slot          uint32                 `protobuf:"varint,6,opt,name=slot,proto3" json:"slot,omitempty"`
	Function      uint32                 `protobuf:"varint,7,opt,name=function,proto3" json:"function,omitempty"`
	Driver        string                 `protobuf:"bytes,8,opt,name=driver,proto3" json:"driver,omitempty"`
	Vendor        string                 `protobuf:"bytes,9,opt,name=vendor,proto3" json:"vendor,omitempty"`
	VendorId      string                 `protobuf:"bytes,10,opt,name=vendor_id,json=vendorId,proto3" json:"vendor_id,omitempty"`
	Product       string                 `protobuf:"bytes,11,opt,name=product,proto3" json:"product,omitempty"`
	ProductId     string                 `protobuf:"bytes,12,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Class         string                 `protobuf:"bytes,13,opt,name=class,proto3" json:"class,omitempty"`
	IommuGroup    int32                  `protobuf:"varint,14,opt,name=iommu_group,json=iommuGroup,proto3" json:"iommu_group,omitempty"`
	NumaNode      int32                  `protobuf:"varint,15,opt,name=numa_node,json=numaNode,proto3" json:"numa_node,omitempty"`
	ManagedByVfio bool                   `protobuf:"varint,16,opt,name=managed_by_vfio,json=managedByVfio,proto3" json:"managed_by_vfio,omitempty"`
	AttachedToVms []string               `protobuf:"bytes,17,rep,name=attached_to_vms,json=attachedToVms,proto3" json:"attached_to_vms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostGPU) Reset() {
	*x = HostGPU{}
	mi := &file_pci_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostGPU) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostGPU) ProtoMessage() {}

func (x *HostGPU) ProtoReflect() protoreflect.Message {
	mi := &file_pci_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostGPU.ProtoReflect.Descriptor instead.
func (*HostGPU) Descriptor() ([]byte, []int) {
	return file_pci_proto_rawDescGZIP(), []int{5}
}

func (x *HostGPU) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *HostGPU) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *HostGPU) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *HostGPU) GetDomain() uint32 {
	if x != nil {
		return x.Domain
	}
	return 0
}

func (x *HostGPU) GetBus() uint32 {
	if x != nil {
		return x.Bus
	}
	return 0
}

func (x *HostGPU) GetSlot() uint32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *HostGPU) GetFunction() uint32 {
	if x != nil {
		return x.Function
	}
	return 0
}

func (x *HostGPU) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *HostGPU) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *HostGPU) GetVendorId() string {
	if x != nil {
		return x.VendorId
	}
	return ""
}

func (x *HostGPU) GetProduct() string {
	if x != nil {
		return x.Product
	}
	return ""
}

func (x *HostGPU) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *HostGPU) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

func (x *HostGPU) GetIommuGroup() int32 {
	if x != nil {
		return x.IommuGroup
	}
	return 0
}

func (x *HostGPU) GetNumaNode() int32 {
	if x != nil {
		return x.NumaNode
	}
	return 0
}

func (x *HostGPU) GetManagedByVfio() bool {
	if x != nil {
		return x.ManagedByVfio
	}
	return false
}

func (x *HostGPU) GetAttachedToVms() []string {
	if x != nil {
		return x.AttachedToVms
	}
	return nil
}

type VMGPU struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Domain        uint32                 `protobuf:"varint,2,opt,name=domain,proto3" json:"domain,omitempty"`
	Bus           uint32                 `protobuf:"varint,3,opt,name=bus,proto3" json:"bus,omitempty"`
	Slot          uint32                 `protobuf:"varint,4,opt,name=slot,proto3" json:"slot,omitempty"`
	Function      uint32                 `protobuf:"varint,5,opt,name=function,proto3" json:"function,omitempty"`
	Managed       bool                   `protobuf:"varint,6,opt,name=managed,proto3" json:"managed,omitempty"`
	Alias         string                 `protobuf:"bytes,7,opt,name=alias,proto3" json:"alias,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VMGPU) Reset() {
	*x = VMGPU{}
	mi := &file_pci_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VMGPU) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VMGPU) ProtoMessage() {}

func (x *VMGPU) ProtoReflect() protoreflect.Message {
	mi := &file_pci_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VMGPU.ProtoReflect.Descriptor instead.
func (*VMGPU) Descriptor() ([]byte, []int) {
	return file_pci_proto_rawDescGZIP(), []int{6}
}

func (x *VMGPU) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *VMGPU) GetDomain() uint32 {
	if x != nil {
		return x.Domain
	}
	return 0
}

func (x *VMGPU) GetBus() uint32 {
	if x != nil {
		return x.Bus
	}
	return 0
}

func (x *VMGPU) GetSlot() uint32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *VMGPU) GetFunction() uint32 {
	if x != nil {
		return x.Function
	}
	return 0
}

func (x *VMGPU) GetManaged() bool {
	if x != nil {
		return x.Managed
	}
	return false
}

func (x *VMGPU) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

type HostGPUList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gpus          []*HostGPU             `protobuf:"bytes,1,rep,name=gpus,proto3" json:"gpus,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostGPUList) Reset() {
	*x = HostGPUList{}
	mi := &file_pci_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostGPUList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostGPUList) ProtoMessage() {}

func (x *HostGPUList) ProtoReflect() protoreflect.Message {
	mi := &file_pci_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostGPUList.ProtoReflect.Descriptor instead.
func (*HostGPUList) Descriptor() ([]byte, []int) {
	return file_pci_proto_rawDescGZIP(), []int{7}
}

func (x *HostGPUList) GetGpus() []*HostGPU {
	if x != nil {
		return x.Gpus
	}
	return nil
}

type VMGPUList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gpus          []*VMGPU               `protobuf:"bytes,1,rep,name=gpus,proto3" json:"gpus,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VMGPUList) Reset() {
	*x = VMGPUList{}
	mi := &file_pci_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VMGPUList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VMGPUList) ProtoMessage() {}

func (x *VMGPUList) ProtoReflect() protoreflect.Message {
	mi := &file_pci_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VMGPUList.ProtoReflect.Descriptor instead.
func (*VMGPUList) Descriptor() ([]byte, []int) {
	return file_pci_proto_rawDescGZIP(), []int{8}
}

func (x *VMGPUList) GetGpus() []*VMGPU {
	if x != nil {
		return x.Gpus
	}
	return nil
}

var File_pci_proto protoreflect.FileDescriptor

const file_pci_proto_rawDesc = "" +
	"\n" +
	"\tpci.proto\x12\x03pci\"\a\n" +
	"\x05Empty\"6\n" +
	"\n" +
	"OkResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"(\n" +
	"\rVmNameRequest\x12\x17\n" +
	"\avm_name\x18\x01 \x01(\tR\x06vmName\".\n" +
	"\x13GPUReferenceRequest\x12\x17\n" +
	"\agpu_ref\x18\x01 \x01(\tR\x06gpuRef\"@\n" +
	"\fVMGPURequest\x12\x17\n" +
	"\avm_name\x18\x01 \x01(\tR\x06vmName\x12\x17\n" +
	"\agpu_ref\x18\x02 \x01(\tR\x06gpuRef\"\xd8\x03\n" +
	"\aHostGPU\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x16\n" +
	"\x06domain\x18\x04 \x01(\rR\x06domain\x12\x10\n" +
	"\x03bus\x18\x05 \x01(\rR\x03bus\x12\x12\n" +
	"\x04slot\x18\x06 \x01(\rR\x04slot\x12\x1a\n" +
	"\bfunction\x18\a \x01(\rR\bfunction\x12\x16\n" +
	"\x06driver\x18\b \x01(\tR\x06driver\x12\x16\n" +
	"\x06vendor\x18\t \x01(\tR\x06vendor\x12\x1b\n" +
	"\tvendor_id\x18\n" +
	" \x01(\tR\bvendorId\x12\x18\n" +
	"\aproduct\x18\v \x01(\tR\aproduct\x12\x1d\n" +
	"\n" +
	"product_id\x18\f \x01(\tR\tproductId\x12\x14\n" +
	"\x05class\x18\r \x01(\tR\x05class\x12\x1f\n" +
	"\viommu_group\x18\x0e \x01(\x05R\n" +
	"iommuGroup\x12\x1b\n" +
	"\tnuma_node\x18\x0f \x01(\x05R\bnumaNode\x12&\n" +
	"\x0fmanaged_by_vfio\x18\x10 \x01(\bR\rmanagedByVfio\x12&\n" +
	"\x0fattached_to_vms\x18\x11 \x03(\tR\rattachedToVms\"\xab\x01\n" +
	"\x05VMGPU\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\rR\x06domain\x12\x10\n" +
	"\x03bus\x18\x03 \x01(\rR\x03bus\x12\x12\n" +
	"\x04slot\x18\x04 \x01(\rR\x04slot\x12\x1a\n" +
	"\bfunction\x18\x05 \x01(\rR\bfunction\x12\x18\n" +
	"\amanaged\x18\x06 \x01(\bR\amanaged\x12\x14\n" +
	"\x05alias\x18\a \x01(\tR\x05alias\"/\n" +
	"\vHostGPUList\x12 \n" +
	"\x04gpus\x18\x01 \x03(\v2\f.pci.HostGPUR\x04gpus\"+\n" +
	"\tVMGPUList\x12\x1e\n" +
	"\x04gpus\x18\x01 \x03(\v2\n" +
	".pci.VMGPUR\x04gpus2\xd2\x02\n" +
	"\x0fSlavePCIService\x12,\n" +
	"\fListHostGPUs\x12\n" +
	".pci.Empty\x1a\x10.pci.HostGPUList\x125\n" +
	"\x15ListHostGPUsWithIOMMU\x12\n" +
	".pci.Empty\x1a\x10.pci.HostGPUList\x120\n" +
	"\n" +
	"ListVMGPUs\x12\x12.pci.VmNameRequest\x1a\x0e.pci.VMGPUList\x123\n" +
	"\rAttachGPUToVM\x12\x11.pci.VMGPURequest\x1a\x0f.pci.OkResponse\x125\n" +
	"\x0fDetachGPUFromVM\x12\x11.pci.VMGPURequest\x1a\x0f.pci.OkResponse\x12<\n" +
	"\x0fReturnGPUToHost\x12\x18.pci.GPUReferenceRequest\x1a\x0f.pci.OkResponseB1Z/github.com/Maruqes/512SvMan/api/proto/pci;protob\x06proto3"

var (
	file_pci_proto_rawDescOnce sync.Once
	file_pci_proto_rawDescData []byte
)

func file_pci_proto_rawDescGZIP() []byte {
	file_pci_proto_rawDescOnce.Do(func() {
		file_pci_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pci_proto_rawDesc), len(file_pci_proto_rawDesc)))
	})
	return file_pci_proto_rawDescData
}

var file_pci_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_pci_proto_goTypes = []any{
	(*Empty)(nil),               // 0: pci.Empty
	(*OkResponse)(nil),          // 1: pci.OkResponse
	(*VmNameRequest)(nil),       // 2: pci.VmNameRequest
	(*GPUReferenceRequest)(nil), // 3: pci.GPUReferenceRequest
	(*VMGPURequest)(nil),        // 4: pci.VMGPURequest
	(*HostGPU)(nil),             // 5: pci.HostGPU
	(*VMGPU)(nil),               // 6: pci.VMGPU
	(*HostGPUList)(nil),         // 7: pci.HostGPUList
	(*VMGPUList)(nil),           // 8: pci.VMGPUList
}
var file_pci_proto_depIdxs = []int32{
	5, // 0: pci.HostGPUList.gpus:type_name -> pci.HostGPU
	6, // 1: pci.VMGPUList.gpus:type_name -> pci.VMGPU
	0, // 2: pci.SlavePCIService.ListHostGPUs:input_type -> pci.Empty
	0, // 3: pci.SlavePCIService.ListHostGPUsWithIOMMU:input_type -> pci.Empty
	2, // 4: pci.SlavePCIService.ListVMGPUs:input_type -> pci.VmNameRequest
	4, // 5: pci.SlavePCIService.AttachGPUToVM:input_type -> pci.VMGPURequest
	4, // 6: pci.SlavePCIService.DetachGPUFromVM:input_type -> pci.VMGPURequest
	3, // 7: pci.SlavePCIService.ReturnGPUToHost:input_type -> pci.GPUReferenceRequest
	7, // 8: pci.SlavePCIService.ListHostGPUs:output_type -> pci.HostGPUList
	7, // 9: pci.SlavePCIService.ListHostGPUsWithIOMMU:output_type -> pci.HostGPUList
	8, // 10: pci.SlavePCIService.ListVMGPUs:output_type -> pci.VMGPUList
	1, // 11: pci.SlavePCIService.AttachGPUToVM:output_type -> pci.OkResponse
	1, // 12: pci.SlavePCIService.DetachGPUFromVM:output_type -> pci.OkResponse
	1, // 13: pci.SlavePCIService.ReturnGPUToHost:output_type -> pci.OkResponse
	8, // [8:14] is the sub-list for method output_type
	2, // [2:8] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pci_proto_init() }
func file_pci_proto_init() {
	if File_pci_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pci_proto_rawDesc), len(file_pci_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pci_proto_goTypes,
		DependencyIndexes: file_pci_proto_depIdxs,
		MessageInfos:      file_pci_proto_msgTypes,
	}.Build()
	File_pci_proto = out.File
	file_pci_proto_goTypes = nil
	file_pci_proto_depIdxs = nil
}
