// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.19.6
// source: extra.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WebSocketsMessageType int32

const (
	WebSocketsMessageType_DownloadIso WebSocketsMessageType = 0
)

// Enum value maps for WebSocketsMessageType.
var (
	WebSocketsMessageType_name = map[int32]string{
		0: "DownloadIso",
	}
	WebSocketsMessageType_value = map[string]int32{
		"DownloadIso": 0,
	}
)

func (x WebSocketsMessageType) Enum() *WebSocketsMessageType {
	p := new(WebSocketsMessageType)
	*p = x
	return p
}

func (x WebSocketsMessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WebSocketsMessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_extra_proto_enumTypes[0].Descriptor()
}

func (WebSocketsMessageType) Type() protoreflect.EnumType {
	return &file_extra_proto_enumTypes[0]
}

func (x WebSocketsMessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WebSocketsMessageType.Descriptor instead.
func (WebSocketsMessageType) EnumDescriptor() ([]byte, []int) {
	return file_extra_proto_rawDescGZIP(), []int{0}
}

type WebsocketMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          WebSocketsMessageType  `protobuf:"varint,1,opt,name=type,proto3,enum=extra.WebSocketsMessageType" json:"type,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebsocketMessage) Reset() {
	*x = WebsocketMessage{}
	mi := &file_extra_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebsocketMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebsocketMessage) ProtoMessage() {}

func (x *WebsocketMessage) ProtoReflect() protoreflect.Message {
	mi := &file_extra_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebsocketMessage.ProtoReflect.Descriptor instead.
func (*WebsocketMessage) Descriptor() ([]byte, []int) {
	return file_extra_proto_rawDescGZIP(), []int{0}
}

func (x *WebsocketMessage) GetType() WebSocketsMessageType {
	if x != nil {
		return x.Type
	}
	return WebSocketsMessageType_DownloadIso
}

func (x *WebsocketMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_extra_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_extra_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_extra_proto_rawDescGZIP(), []int{1}
}

type UpdateInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateInfo) Reset() {
	*x = UpdateInfo{}
	mi := &file_extra_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateInfo) ProtoMessage() {}

func (x *UpdateInfo) ProtoReflect() protoreflect.Message {
	mi := &file_extra_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateInfo.ProtoReflect.Descriptor instead.
func (*UpdateInfo) Descriptor() ([]byte, []int) {
	return file_extra_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type AllUpdates struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Updates       []*UpdateInfo          `protobuf:"bytes,1,rep,name=updates,proto3" json:"updates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllUpdates) Reset() {
	*x = AllUpdates{}
	mi := &file_extra_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllUpdates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllUpdates) ProtoMessage() {}

func (x *AllUpdates) ProtoReflect() protoreflect.Message {
	mi := &file_extra_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllUpdates.ProtoReflect.Descriptor instead.
func (*AllUpdates) Descriptor() ([]byte, []int) {
	return file_extra_proto_rawDescGZIP(), []int{3}
}

func (x *AllUpdates) GetUpdates() []*UpdateInfo {
	if x != nil {
		return x.Updates
	}
	return nil
}

type UpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` //if empty means all
	RestartAfter  bool                   `protobuf:"varint,2,opt,name=restartAfter,proto3" json:"restartAfter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_extra_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_extra_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_extra_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateRequest) GetRestartAfter() bool {
	if x != nil {
		return x.RestartAfter
	}
	return false
}

var File_extra_proto protoreflect.FileDescriptor

const file_extra_proto_rawDesc = "" +
	"\n" +
	"\vextra.proto\x12\x05extra\"^\n" +
	"\x10WebsocketMessage\x120\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1c.extra.WebSocketsMessageTypeR\x04type\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\a\n" +
	"\x05Empty\":\n" +
	"\n" +
	"UpdateInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"9\n" +
	"\n" +
	"AllUpdates\x12+\n" +
	"\aupdates\x18\x01 \x03(\v2\x11.extra.UpdateInfoR\aupdates\"G\n" +
	"\rUpdateRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\"\n" +
	"\frestartAfter\x18\x02 \x01(\bR\frestartAfter*(\n" +
	"\x15WebSocketsMessageType\x12\x0f\n" +
	"\vDownloadIso\x10\x002\xb6\x01\n" +
	"\fExtraService\x12=\n" +
	"\x14SendWebsocketMessage\x12\x17.extra.WebsocketMessage\x1a\f.extra.Empty\x122\n" +
	"\x0fCheckForUpdates\x12\f.extra.Empty\x1a\x11.extra.AllUpdates\x123\n" +
	"\rPerformUpdate\x12\x14.extra.UpdateRequest\x1a\f.extra.EmptyB3Z1github.com/Maruqes/512SvMan/api/proto/extra;protob\x06proto3"

var (
	file_extra_proto_rawDescOnce sync.Once
	file_extra_proto_rawDescData []byte
)

func file_extra_proto_rawDescGZIP() []byte {
	file_extra_proto_rawDescOnce.Do(func() {
		file_extra_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_extra_proto_rawDesc), len(file_extra_proto_rawDesc)))
	})
	return file_extra_proto_rawDescData
}

var file_extra_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_extra_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_extra_proto_goTypes = []any{
	(WebSocketsMessageType)(0), // 0: extra.WebSocketsMessageType
	(*WebsocketMessage)(nil),   // 1: extra.WebsocketMessage
	(*Empty)(nil),              // 2: extra.Empty
	(*UpdateInfo)(nil),         // 3: extra.UpdateInfo
	(*AllUpdates)(nil),         // 4: extra.AllUpdates
	(*UpdateRequest)(nil),      // 5: extra.UpdateRequest
}
var file_extra_proto_depIdxs = []int32{
	0, // 0: extra.WebsocketMessage.type:type_name -> extra.WebSocketsMessageType
	3, // 1: extra.AllUpdates.updates:type_name -> extra.UpdateInfo
	1, // 2: extra.ExtraService.SendWebsocketMessage:input_type -> extra.WebsocketMessage
	2, // 3: extra.ExtraService.CheckForUpdates:input_type -> extra.Empty
	5, // 4: extra.ExtraService.PerformUpdate:input_type -> extra.UpdateRequest
	2, // 5: extra.ExtraService.SendWebsocketMessage:output_type -> extra.Empty
	4, // 6: extra.ExtraService.CheckForUpdates:output_type -> extra.AllUpdates
	2, // 7: extra.ExtraService.PerformUpdate:output_type -> extra.Empty
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_extra_proto_init() }
func file_extra_proto_init() {
	if File_extra_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_extra_proto_rawDesc), len(file_extra_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_extra_proto_goTypes,
		DependencyIndexes: file_extra_proto_depIdxs,
		EnumInfos:         file_extra_proto_enumTypes,
		MessageInfos:      file_extra_proto_msgTypes,
	}.Build()
	File_extra_proto = out.File
	file_extra_proto_goTypes = nil
	file_extra_proto_depIdxs = nil
}
