// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.6
// source: protocol.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetConnectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MachineName   string                 `protobuf:"bytes,1,opt,name=machineName,proto3" json:"machineName,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetConnectionRequest) Reset() {
	*x = SetConnectionRequest{}
	mi := &file_protocol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetConnectionRequest) ProtoMessage() {}

func (x *SetConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetConnectionRequest.ProtoReflect.Descriptor instead.
func (*SetConnectionRequest) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{0}
}

func (x *SetConnectionRequest) GetMachineName() string {
	if x != nil {
		return x.MachineName
	}
	return ""
}

func (x *SetConnectionRequest) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

type SetConnectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            string                 `protobuf:"bytes,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetConnectionResponse) Reset() {
	*x = SetConnectionResponse{}
	mi := &file_protocol_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetConnectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetConnectionResponse) ProtoMessage() {}

func (x *SetConnectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetConnectionResponse.ProtoReflect.Descriptor instead.
func (*SetConnectionResponse) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{1}
}

func (x *SetConnectionResponse) GetOk() string {
	if x != nil {
		return x.Ok
	}
	return ""
}

type NotifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyRequest) Reset() {
	*x = NotifyRequest{}
	mi := &file_protocol_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyRequest) ProtoMessage() {}

func (x *NotifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyRequest.ProtoReflect.Descriptor instead.
func (*NotifyRequest) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{2}
}

func (x *NotifyRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type NotifyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            string                 `protobuf:"bytes,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyResponse) Reset() {
	*x = NotifyResponse{}
	mi := &file_protocol_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyResponse) ProtoMessage() {}

func (x *NotifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyResponse.ProtoReflect.Descriptor instead.
func (*NotifyResponse) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{3}
}

func (x *NotifyResponse) GetOk() string {
	if x != nil {
		return x.Ok
	}
	return ""
}

var File_protocol_proto protoreflect.FileDescriptor

const file_protocol_proto_rawDesc = "" +
	"\n" +
	"\x0eprotocol.proto\x12\bprotocol\"L\n" +
	"\x14SetConnectionRequest\x12 \n" +
	"\vmachineName\x18\x01 \x01(\tR\vmachineName\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\"'\n" +
	"\x15SetConnectionResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\tR\x02ok\"#\n" +
	"\rNotifyRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\" \n" +
	"\x0eNotifyResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\tR\x02ok2\xa0\x01\n" +
	"\x0fProtocolService\x12P\n" +
	"\rSetConnection\x12\x1e.protocol.SetConnectionRequest\x1a\x1f.protocol.SetConnectionResponse\x12;\n" +
	"\x06Notify\x12\x17.protocol.NotifyRequest\x1a\x18.protocol.NotifyResponse2L\n" +
	"\rClientService\x12;\n" +
	"\x06Notify\x12\x17.protocol.NotifyRequest\x1a\x18.protocol.NotifyResponseB6Z4github.com/Maruqes/512SvMan/api/proto/protocol;protob\x06proto3"

var (
	file_protocol_proto_rawDescOnce sync.Once
	file_protocol_proto_rawDescData []byte
)

func file_protocol_proto_rawDescGZIP() []byte {
	file_protocol_proto_rawDescOnce.Do(func() {
		file_protocol_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protocol_proto_rawDesc), len(file_protocol_proto_rawDesc)))
	})
	return file_protocol_proto_rawDescData
}

var file_protocol_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protocol_proto_goTypes = []any{
	(*SetConnectionRequest)(nil),  // 0: protocol.SetConnectionRequest
	(*SetConnectionResponse)(nil), // 1: protocol.SetConnectionResponse
	(*NotifyRequest)(nil),         // 2: protocol.NotifyRequest
	(*NotifyResponse)(nil),        // 3: protocol.NotifyResponse
}
var file_protocol_proto_depIdxs = []int32{
	0, // 0: protocol.ProtocolService.SetConnection:input_type -> protocol.SetConnectionRequest
	2, // 1: protocol.ProtocolService.Notify:input_type -> protocol.NotifyRequest
	2, // 2: protocol.ClientService.Notify:input_type -> protocol.NotifyRequest
	1, // 3: protocol.ProtocolService.SetConnection:output_type -> protocol.SetConnectionResponse
	3, // 4: protocol.ProtocolService.Notify:output_type -> protocol.NotifyResponse
	3, // 5: protocol.ClientService.Notify:output_type -> protocol.NotifyResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protocol_proto_init() }
func file_protocol_proto_init() {
	if File_protocol_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protocol_proto_rawDesc), len(file_protocol_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_protocol_proto_goTypes,
		DependencyIndexes: file_protocol_proto_depIdxs,
		MessageInfos:      file_protocol_proto_msgTypes,
	}.Build()
	File_protocol_proto = out.File
	file_protocol_proto_goTypes = nil
	file_protocol_proto_depIdxs = nil
}
