// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.6
// source: smartdisk.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	SmartDiskService_GetSmartInfo_FullMethodName                    = "/smartdisk.SmartDiskService/GetSmartInfo"
	SmartDiskService_RunSelfTest_FullMethodName                     = "/smartdisk.SmartDiskService/RunSelfTest"
	SmartDiskService_GetSelfTestProgress_FullMethodName             = "/smartdisk.SmartDiskService/GetSelfTestProgress"
	SmartDiskService_CancelSelfTest_FullMethodName                  = "/smartdisk.SmartDiskService/CancelSelfTest"
	SmartDiskService_StartForceReallocation_FullMethodName          = "/smartdisk.SmartDiskService/StartForceReallocation"
	SmartDiskService_GetForceReallocationProgress_FullMethodName    = "/smartdisk.SmartDiskService/GetForceReallocationProgress"
	SmartDiskService_GetAllForceReallocationProgress_FullMethodName = "/smartdisk.SmartDiskService/GetAllForceReallocationProgress"
	SmartDiskService_CancelForceReallocation_FullMethodName         = "/smartdisk.SmartDiskService/CancelForceReallocation"
)

// SmartDiskServiceClient is the client API for SmartDiskService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SmartDiskServiceClient interface {
	GetSmartInfo(ctx context.Context, in *SmartInfoRequest, opts ...grpc.CallOption) (*SmartDiskInfo, error)
	RunSelfTest(ctx context.Context, in *SelfTestRequest, opts ...grpc.CallOption) (*SelfTestResponse, error)
	GetSelfTestProgress(ctx context.Context, in *SmartInfoRequest, opts ...grpc.CallOption) (*SelfTestProgress, error)
	CancelSelfTest(ctx context.Context, in *CancelSelfTestRequest, opts ...grpc.CallOption) (*SelfTestResponse, error)
	StartForceReallocation(ctx context.Context, in *ForceReallocRequest, opts ...grpc.CallOption) (*ForceReallocResponse, error)
	GetForceReallocationProgress(ctx context.Context, in *ForceReallocRequest, opts ...grpc.CallOption) (*ForceReallocProgress, error)
	GetAllForceReallocationProgress(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ForceReallocProgressList, error)
	CancelForceReallocation(ctx context.Context, in *ForceReallocRequest, opts ...grpc.CallOption) (*ForceReallocResponse, error)
}

type smartDiskServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSmartDiskServiceClient(cc grpc.ClientConnInterface) SmartDiskServiceClient {
	return &smartDiskServiceClient{cc}
}

func (c *smartDiskServiceClient) GetSmartInfo(ctx context.Context, in *SmartInfoRequest, opts ...grpc.CallOption) (*SmartDiskInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SmartDiskInfo)
	err := c.cc.Invoke(ctx, SmartDiskService_GetSmartInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smartDiskServiceClient) RunSelfTest(ctx context.Context, in *SelfTestRequest, opts ...grpc.CallOption) (*SelfTestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SelfTestResponse)
	err := c.cc.Invoke(ctx, SmartDiskService_RunSelfTest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smartDiskServiceClient) GetSelfTestProgress(ctx context.Context, in *SmartInfoRequest, opts ...grpc.CallOption) (*SelfTestProgress, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SelfTestProgress)
	err := c.cc.Invoke(ctx, SmartDiskService_GetSelfTestProgress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smartDiskServiceClient) CancelSelfTest(ctx context.Context, in *CancelSelfTestRequest, opts ...grpc.CallOption) (*SelfTestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SelfTestResponse)
	err := c.cc.Invoke(ctx, SmartDiskService_CancelSelfTest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smartDiskServiceClient) StartForceReallocation(ctx context.Context, in *ForceReallocRequest, opts ...grpc.CallOption) (*ForceReallocResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForceReallocResponse)
	err := c.cc.Invoke(ctx, SmartDiskService_StartForceReallocation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smartDiskServiceClient) GetForceReallocationProgress(ctx context.Context, in *ForceReallocRequest, opts ...grpc.CallOption) (*ForceReallocProgress, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForceReallocProgress)
	err := c.cc.Invoke(ctx, SmartDiskService_GetForceReallocationProgress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smartDiskServiceClient) GetAllForceReallocationProgress(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ForceReallocProgressList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForceReallocProgressList)
	err := c.cc.Invoke(ctx, SmartDiskService_GetAllForceReallocationProgress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smartDiskServiceClient) CancelForceReallocation(ctx context.Context, in *ForceReallocRequest, opts ...grpc.CallOption) (*ForceReallocResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForceReallocResponse)
	err := c.cc.Invoke(ctx, SmartDiskService_CancelForceReallocation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SmartDiskServiceServer is the server API for SmartDiskService service.
// All implementations must embed UnimplementedSmartDiskServiceServer
// for forward compatibility
type SmartDiskServiceServer interface {
	GetSmartInfo(context.Context, *SmartInfoRequest) (*SmartDiskInfo, error)
	RunSelfTest(context.Context, *SelfTestRequest) (*SelfTestResponse, error)
	GetSelfTestProgress(context.Context, *SmartInfoRequest) (*SelfTestProgress, error)
	CancelSelfTest(context.Context, *CancelSelfTestRequest) (*SelfTestResponse, error)
	StartForceReallocation(context.Context, *ForceReallocRequest) (*ForceReallocResponse, error)
	GetForceReallocationProgress(context.Context, *ForceReallocRequest) (*ForceReallocProgress, error)
	GetAllForceReallocationProgress(context.Context, *Empty) (*ForceReallocProgressList, error)
	CancelForceReallocation(context.Context, *ForceReallocRequest) (*ForceReallocResponse, error)
	mustEmbedUnimplementedSmartDiskServiceServer()
}

// UnimplementedSmartDiskServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSmartDiskServiceServer struct {
}

func (UnimplementedSmartDiskServiceServer) GetSmartInfo(context.Context, *SmartInfoRequest) (*SmartDiskInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSmartInfo not implemented")
}
func (UnimplementedSmartDiskServiceServer) RunSelfTest(context.Context, *SelfTestRequest) (*SelfTestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunSelfTest not implemented")
}
func (UnimplementedSmartDiskServiceServer) GetSelfTestProgress(context.Context, *SmartInfoRequest) (*SelfTestProgress, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSelfTestProgress not implemented")
}
func (UnimplementedSmartDiskServiceServer) CancelSelfTest(context.Context, *CancelSelfTestRequest) (*SelfTestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelSelfTest not implemented")
}
func (UnimplementedSmartDiskServiceServer) StartForceReallocation(context.Context, *ForceReallocRequest) (*ForceReallocResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartForceReallocation not implemented")
}
func (UnimplementedSmartDiskServiceServer) GetForceReallocationProgress(context.Context, *ForceReallocRequest) (*ForceReallocProgress, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetForceReallocationProgress not implemented")
}
func (UnimplementedSmartDiskServiceServer) GetAllForceReallocationProgress(context.Context, *Empty) (*ForceReallocProgressList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllForceReallocationProgress not implemented")
}
func (UnimplementedSmartDiskServiceServer) CancelForceReallocation(context.Context, *ForceReallocRequest) (*ForceReallocResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelForceReallocation not implemented")
}
func (UnimplementedSmartDiskServiceServer) mustEmbedUnimplementedSmartDiskServiceServer() {}

// UnsafeSmartDiskServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SmartDiskServiceServer will
// result in compilation errors.
type UnsafeSmartDiskServiceServer interface {
	mustEmbedUnimplementedSmartDiskServiceServer()
}

func RegisterSmartDiskServiceServer(s grpc.ServiceRegistrar, srv SmartDiskServiceServer) {
	s.RegisterService(&SmartDiskService_ServiceDesc, srv)
}

func _SmartDiskService_GetSmartInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SmartInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmartDiskServiceServer).GetSmartInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SmartDiskService_GetSmartInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmartDiskServiceServer).GetSmartInfo(ctx, req.(*SmartInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SmartDiskService_RunSelfTest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SelfTestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmartDiskServiceServer).RunSelfTest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SmartDiskService_RunSelfTest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmartDiskServiceServer).RunSelfTest(ctx, req.(*SelfTestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SmartDiskService_GetSelfTestProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SmartInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmartDiskServiceServer).GetSelfTestProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SmartDiskService_GetSelfTestProgress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmartDiskServiceServer).GetSelfTestProgress(ctx, req.(*SmartInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SmartDiskService_CancelSelfTest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelSelfTestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmartDiskServiceServer).CancelSelfTest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SmartDiskService_CancelSelfTest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmartDiskServiceServer).CancelSelfTest(ctx, req.(*CancelSelfTestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SmartDiskService_StartForceReallocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForceReallocRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmartDiskServiceServer).StartForceReallocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SmartDiskService_StartForceReallocation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmartDiskServiceServer).StartForceReallocation(ctx, req.(*ForceReallocRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SmartDiskService_GetForceReallocationProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForceReallocRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmartDiskServiceServer).GetForceReallocationProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SmartDiskService_GetForceReallocationProgress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmartDiskServiceServer).GetForceReallocationProgress(ctx, req.(*ForceReallocRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SmartDiskService_GetAllForceReallocationProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmartDiskServiceServer).GetAllForceReallocationProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SmartDiskService_GetAllForceReallocationProgress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmartDiskServiceServer).GetAllForceReallocationProgress(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SmartDiskService_CancelForceReallocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForceReallocRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmartDiskServiceServer).CancelForceReallocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SmartDiskService_CancelForceReallocation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmartDiskServiceServer).CancelForceReallocation(ctx, req.(*ForceReallocRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SmartDiskService_ServiceDesc is the grpc.ServiceDesc for SmartDiskService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SmartDiskService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "smartdisk.SmartDiskService",
	HandlerType: (*SmartDiskServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSmartInfo",
			Handler:    _SmartDiskService_GetSmartInfo_Handler,
		},
		{
			MethodName: "RunSelfTest",
			Handler:    _SmartDiskService_RunSelfTest_Handler,
		},
		{
			MethodName: "GetSelfTestProgress",
			Handler:    _SmartDiskService_GetSelfTestProgress_Handler,
		},
		{
			MethodName: "CancelSelfTest",
			Handler:    _SmartDiskService_CancelSelfTest_Handler,
		},
		{
			MethodName: "StartForceReallocation",
			Handler:    _SmartDiskService_StartForceReallocation_Handler,
		},
		{
			MethodName: "GetForceReallocationProgress",
			Handler:    _SmartDiskService_GetForceReallocationProgress_Handler,
		},
		{
			MethodName: "GetAllForceReallocationProgress",
			Handler:    _SmartDiskService_GetAllForceReallocationProgress_Handler,
		},
		{
			MethodName: "CancelForceReallocation",
			Handler:    _SmartDiskService_CancelForceReallocation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "smartdisk.proto",
}
