// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.6
// source: vm_disk.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VMDiskService_CreateVMDisk_FullMethodName  = "/vm_disk.VMDiskService/CreateVMDisk"
	VMDiskService_DeleteVMDisk_FullMethodName  = "/vm_disk.VMDiskService/DeleteVMDisk"
	VMDiskService_GrowVMDisk_FullMethodName    = "/vm_disk.VMDiskService/GrowVMDisk"
	VMDiskService_GetVMDiskInfo_FullMethodName = "/vm_disk.VMDiskService/GetVMDiskInfo"
)

// VMDiskServiceClient is the client API for VMDiskService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VMDiskServiceClient interface {
	CreateVMDisk(ctx context.Context, in *CreateVMDiskRequest, opts ...grpc.CallOption) (*VMDiskResponse, error)
	DeleteVMDisk(ctx context.Context, in *VMDiskByNameRequest, opts ...grpc.CallOption) (*VMDiskResponse, error)
	GrowVMDisk(ctx context.Context, in *GrowVMDiskRequest, opts ...grpc.CallOption) (*VMDiskResponse, error)
	GetVMDiskInfo(ctx context.Context, in *VMDiskByNameRequest, opts ...grpc.CallOption) (*VMDiskResponse, error)
}

type vMDiskServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVMDiskServiceClient(cc grpc.ClientConnInterface) VMDiskServiceClient {
	return &vMDiskServiceClient{cc}
}

func (c *vMDiskServiceClient) CreateVMDisk(ctx context.Context, in *CreateVMDiskRequest, opts ...grpc.CallOption) (*VMDiskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VMDiskResponse)
	err := c.cc.Invoke(ctx, VMDiskService_CreateVMDisk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMDiskServiceClient) DeleteVMDisk(ctx context.Context, in *VMDiskByNameRequest, opts ...grpc.CallOption) (*VMDiskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VMDiskResponse)
	err := c.cc.Invoke(ctx, VMDiskService_DeleteVMDisk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMDiskServiceClient) GrowVMDisk(ctx context.Context, in *GrowVMDiskRequest, opts ...grpc.CallOption) (*VMDiskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VMDiskResponse)
	err := c.cc.Invoke(ctx, VMDiskService_GrowVMDisk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMDiskServiceClient) GetVMDiskInfo(ctx context.Context, in *VMDiskByNameRequest, opts ...grpc.CallOption) (*VMDiskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VMDiskResponse)
	err := c.cc.Invoke(ctx, VMDiskService_GetVMDiskInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VMDiskServiceServer is the server API for VMDiskService service.
// All implementations must embed UnimplementedVMDiskServiceServer
// for forward compatibility.
type VMDiskServiceServer interface {
	CreateVMDisk(context.Context, *CreateVMDiskRequest) (*VMDiskResponse, error)
	DeleteVMDisk(context.Context, *VMDiskByNameRequest) (*VMDiskResponse, error)
	GrowVMDisk(context.Context, *GrowVMDiskRequest) (*VMDiskResponse, error)
	GetVMDiskInfo(context.Context, *VMDiskByNameRequest) (*VMDiskResponse, error)
	mustEmbedUnimplementedVMDiskServiceServer()
}

// UnimplementedVMDiskServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVMDiskServiceServer struct{}

func (UnimplementedVMDiskServiceServer) CreateVMDisk(context.Context, *CreateVMDiskRequest) (*VMDiskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateVMDisk not implemented")
}
func (UnimplementedVMDiskServiceServer) DeleteVMDisk(context.Context, *VMDiskByNameRequest) (*VMDiskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteVMDisk not implemented")
}
func (UnimplementedVMDiskServiceServer) GrowVMDisk(context.Context, *GrowVMDiskRequest) (*VMDiskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GrowVMDisk not implemented")
}
func (UnimplementedVMDiskServiceServer) GetVMDiskInfo(context.Context, *VMDiskByNameRequest) (*VMDiskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVMDiskInfo not implemented")
}
func (UnimplementedVMDiskServiceServer) mustEmbedUnimplementedVMDiskServiceServer() {}
func (UnimplementedVMDiskServiceServer) testEmbeddedByValue()                       {}

// UnsafeVMDiskServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VMDiskServiceServer will
// result in compilation errors.
type UnsafeVMDiskServiceServer interface {
	mustEmbedUnimplementedVMDiskServiceServer()
}

func RegisterVMDiskServiceServer(s grpc.ServiceRegistrar, srv VMDiskServiceServer) {
	// If the following call pancis, it indicates UnimplementedVMDiskServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VMDiskService_ServiceDesc, srv)
}

func _VMDiskService_CreateVMDisk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVMDiskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMDiskServiceServer).CreateVMDisk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VMDiskService_CreateVMDisk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMDiskServiceServer).CreateVMDisk(ctx, req.(*CreateVMDiskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMDiskService_DeleteVMDisk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VMDiskByNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMDiskServiceServer).DeleteVMDisk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VMDiskService_DeleteVMDisk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMDiskServiceServer).DeleteVMDisk(ctx, req.(*VMDiskByNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMDiskService_GrowVMDisk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrowVMDiskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMDiskServiceServer).GrowVMDisk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VMDiskService_GrowVMDisk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMDiskServiceServer).GrowVMDisk(ctx, req.(*GrowVMDiskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMDiskService_GetVMDiskInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VMDiskByNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMDiskServiceServer).GetVMDiskInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VMDiskService_GetVMDiskInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMDiskServiceServer).GetVMDiskInfo(ctx, req.(*VMDiskByNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VMDiskService_ServiceDesc is the grpc.ServiceDesc for VMDiskService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VMDiskService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vm_disk.VMDiskService",
	HandlerType: (*VMDiskServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateVMDisk",
			Handler:    _VMDiskService_CreateVMDisk_Handler,
		},
		{
			MethodName: "DeleteVMDisk",
			Handler:    _VMDiskService_DeleteVMDisk_Handler,
		},
		{
			MethodName: "GrowVMDisk",
			Handler:    _VMDiskService_GrowVMDisk_Handler,
		},
		{
			MethodName: "GetVMDiskInfo",
			Handler:    _VMDiskService_GetVMDiskInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vm_disk.proto",
}
