// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.19.6
// source: virsh.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// get cpu features
type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_virsh_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_virsh_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_virsh_proto_rawDescGZIP(), []int{0}
}

type GetCpuFeaturesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Features []string `protobuf:"bytes,1,rep,name=features,proto3" json:"features,omitempty"`
}

func (x *GetCpuFeaturesResponse) Reset() {
	*x = GetCpuFeaturesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_virsh_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCpuFeaturesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCpuFeaturesResponse) ProtoMessage() {}

func (x *GetCpuFeaturesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_virsh_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCpuFeaturesResponse.ProtoReflect.Descriptor instead.
func (*GetCpuFeaturesResponse) Descriptor() ([]byte, []int) {
	return file_virsh_proto_rawDescGZIP(), []int{1}
}

func (x *GetCpuFeaturesResponse) GetFeatures() []string {
	if x != nil {
		return x.Features
	}
	return nil
}

type CreateVmRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Memory      int32  `protobuf:"varint,2,opt,name=memory,proto3" json:"memory,omitempty"`
	Vcpu        int32  `protobuf:"varint,3,opt,name=vcpu,proto3" json:"vcpu,omitempty"`
	DiskPath    string `protobuf:"bytes,4,opt,name=disk_path,json=diskPath,proto3" json:"disk_path,omitempty"`
	DiskSizeGB  int32  `protobuf:"varint,5,opt,name=disk_sizeGB,json=diskSizeGB,proto3" json:"disk_sizeGB,omitempty"`
	IsoPath     string `protobuf:"bytes,6,opt,name=iso_path,json=isoPath,proto3" json:"iso_path,omitempty"`
	Network     string `protobuf:"bytes,7,opt,name=network,proto3" json:"network,omitempty"`
	VNCPassword string `protobuf:"bytes,8,opt,name=VNC_password,json=VNCPassword,proto3" json:"VNC_password,omitempty"`
}

func (x *CreateVmRequest) Reset() {
	*x = CreateVmRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_virsh_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateVmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVmRequest) ProtoMessage() {}

func (x *CreateVmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_virsh_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVmRequest.ProtoReflect.Descriptor instead.
func (*CreateVmRequest) Descriptor() ([]byte, []int) {
	return file_virsh_proto_rawDescGZIP(), []int{2}
}

func (x *CreateVmRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateVmRequest) GetMemory() int32 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *CreateVmRequest) GetVcpu() int32 {
	if x != nil {
		return x.Vcpu
	}
	return 0
}

func (x *CreateVmRequest) GetDiskPath() string {
	if x != nil {
		return x.DiskPath
	}
	return ""
}

func (x *CreateVmRequest) GetDiskSizeGB() int32 {
	if x != nil {
		return x.DiskSizeGB
	}
	return 0
}

func (x *CreateVmRequest) GetIsoPath() string {
	if x != nil {
		return x.IsoPath
	}
	return ""
}

func (x *CreateVmRequest) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *CreateVmRequest) GetVNCPassword() string {
	if x != nil {
		return x.VNCPassword
	}
	return ""
}

type OkResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok      bool   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *OkResponse) Reset() {
	*x = OkResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_virsh_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OkResponse) ProtoMessage() {}

func (x *OkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_virsh_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OkResponse.ProtoReflect.Descriptor instead.
func (*OkResponse) Descriptor() ([]byte, []int) {
	return file_virsh_proto_rawDescGZIP(), []int{3}
}

func (x *OkResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *OkResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Vm struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	State     string `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	NovncPort string `protobuf:"bytes,3,opt,name=novncPort,proto3" json:"novncPort,omitempty"`
}

func (x *Vm) Reset() {
	*x = Vm{}
	if protoimpl.UnsafeEnabled {
		mi := &file_virsh_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Vm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vm) ProtoMessage() {}

func (x *Vm) ProtoReflect() protoreflect.Message {
	mi := &file_virsh_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vm.ProtoReflect.Descriptor instead.
func (*Vm) Descriptor() ([]byte, []int) {
	return file_virsh_proto_rawDescGZIP(), []int{4}
}

func (x *Vm) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Vm) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Vm) GetNovncPort() string {
	if x != nil {
		return x.NovncPort
	}
	return ""
}

type GetVmByNameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *GetVmByNameRequest) Reset() {
	*x = GetVmByNameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_virsh_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVmByNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVmByNameRequest) ProtoMessage() {}

func (x *GetVmByNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_virsh_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVmByNameRequest.ProtoReflect.Descriptor instead.
func (*GetVmByNameRequest) Descriptor() ([]byte, []int) {
	return file_virsh_proto_rawDescGZIP(), []int{5}
}

func (x *GetVmByNameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetAllVmsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vms []*Vm `protobuf:"bytes,1,rep,name=vms,proto3" json:"vms,omitempty"`
}

func (x *GetAllVmsResponse) Reset() {
	*x = GetAllVmsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_virsh_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllVmsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllVmsResponse) ProtoMessage() {}

func (x *GetAllVmsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_virsh_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllVmsResponse.ProtoReflect.Descriptor instead.
func (*GetAllVmsResponse) Descriptor() ([]byte, []int) {
	return file_virsh_proto_rawDescGZIP(), []int{6}
}

func (x *GetAllVmsResponse) GetVms() []*Vm {
	if x != nil {
		return x.Vms
	}
	return nil
}

var File_virsh_proto protoreflect.FileDescriptor

var file_virsh_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x76, 0x69, 0x72, 0x73, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x76,
	0x69, 0x72, 0x73, 0x68, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x34, 0x0a,
	0x16, 0x47, 0x65, 0x74, 0x43, 0x70, 0x75, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x65, 0x61, 0x74, 0x75,
	0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x66, 0x65, 0x61, 0x74, 0x75,
	0x72, 0x65, 0x73, 0x22, 0xe7, 0x01, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x56, 0x6d,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6d,
	0x65, 0x6d, 0x6f, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6d, 0x65, 0x6d,
	0x6f, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x76, 0x63, 0x70, 0x75, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x76, 0x63, 0x70, 0x75, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x69, 0x73, 0x6b, 0x5f,
	0x70, 0x61, 0x74, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x69, 0x73, 0x6b,
	0x50, 0x61, 0x74, 0x68, 0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x69, 0x73, 0x6b, 0x5f, 0x73, 0x69, 0x7a,
	0x65, 0x47, 0x42, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x64, 0x69, 0x73, 0x6b, 0x53,
	0x69, 0x7a, 0x65, 0x47, 0x42, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x73, 0x6f, 0x5f, 0x70, 0x61, 0x74,
	0x68, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x69, 0x73, 0x6f, 0x50, 0x61, 0x74, 0x68,
	0x12, 0x18, 0x0a, 0x07, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x12, 0x21, 0x0a, 0x0c, 0x56, 0x4e,
	0x43, 0x5f, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x56, 0x4e, 0x43, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x36, 0x0a,
	0x0a, 0x4f, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f,
	0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x4c, 0x0a, 0x02, 0x56, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x6f, 0x76, 0x6e, 0x63, 0x50, 0x6f,
	0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x6f, 0x76, 0x6e, 0x63, 0x50,
	0x6f, 0x72, 0x74, 0x22, 0x28, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x56, 0x6d, 0x42, 0x79, 0x4e, 0x61,
	0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x30, 0x0a,
	0x11, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x56, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x1b, 0x0a, 0x03, 0x76, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x09, 0x2e, 0x76, 0x69, 0x72, 0x73, 0x68, 0x2e, 0x56, 0x6d, 0x52, 0x03, 0x76, 0x6d, 0x73, 0x32,
	0xda, 0x03, 0x0a, 0x11, 0x53, 0x6c, 0x61, 0x76, 0x65, 0x56, 0x69, 0x72, 0x73, 0x68, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3d, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x43, 0x70, 0x75, 0x46,
	0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x12, 0x0c, 0x2e, 0x76, 0x69, 0x72, 0x73, 0x68, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x1d, 0x2e, 0x76, 0x69, 0x72, 0x73, 0x68, 0x2e, 0x47, 0x65,
	0x74, 0x43, 0x70, 0x75, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x08, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x56, 0x6d,
	0x12, 0x16, 0x2e, 0x76, 0x69, 0x72, 0x73, 0x68, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x56,
	0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x76, 0x69, 0x72, 0x73, 0x68,
	0x2e, 0x4f, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x0c, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x76, 0x65, 0x56, 0x4d, 0x12, 0x0c, 0x2e, 0x76, 0x69,
	0x72, 0x73, 0x68, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x11, 0x2e, 0x76, 0x69, 0x72, 0x73,
	0x68, 0x2e, 0x4f, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x09,
	0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x65, 0x56, 0x4d, 0x12, 0x0c, 0x2e, 0x76, 0x69, 0x72, 0x73,
	0x68, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x11, 0x2e, 0x76, 0x69, 0x72, 0x73, 0x68, 0x2e,
	0x4f, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x0a, 0x53, 0x68,
	0x75, 0x74, 0x64, 0x6f, 0x77, 0x6e, 0x56, 0x4d, 0x12, 0x0c, 0x2e, 0x76, 0x69, 0x72, 0x73, 0x68,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x11, 0x2e, 0x76, 0x69, 0x72, 0x73, 0x68, 0x2e, 0x4f,
	0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x07, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x56, 0x4d, 0x12, 0x0c, 0x2e, 0x76, 0x69, 0x72, 0x73, 0x68, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x1a, 0x11, 0x2e, 0x76, 0x69, 0x72, 0x73, 0x68, 0x2e, 0x4f, 0x6b, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x08, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x56,
	0x4d, 0x12, 0x0c, 0x2e, 0x76, 0x69, 0x72, 0x73, 0x68, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a,
	0x11, 0x2e, 0x76, 0x69, 0x72, 0x73, 0x68, 0x2e, 0x4f, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x33, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x56, 0x6d, 0x73, 0x12,
	0x0c, 0x2e, 0x76, 0x69, 0x72, 0x73, 0x68, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x18, 0x2e,
	0x76, 0x69, 0x72, 0x73, 0x68, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x56, 0x6d, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x56, 0x6d,
	0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x19, 0x2e, 0x76, 0x69, 0x72, 0x73, 0x68, 0x2e, 0x47,
	0x65, 0x74, 0x56, 0x6d, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x09, 0x2e, 0x76, 0x69, 0x72, 0x73, 0x68, 0x2e, 0x56, 0x6d, 0x42, 0x33, 0x5a, 0x31,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4d, 0x61, 0x72, 0x75, 0x71,
	0x65, 0x73, 0x2f, 0x35, 0x31, 0x32, 0x53, 0x76, 0x4d, 0x61, 0x6e, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x69, 0x72, 0x73, 0x68, 0x3b, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_virsh_proto_rawDescOnce sync.Once
	file_virsh_proto_rawDescData = file_virsh_proto_rawDesc
)

func file_virsh_proto_rawDescGZIP() []byte {
	file_virsh_proto_rawDescOnce.Do(func() {
		file_virsh_proto_rawDescData = protoimpl.X.CompressGZIP(file_virsh_proto_rawDescData)
	})
	return file_virsh_proto_rawDescData
}

var file_virsh_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_virsh_proto_goTypes = []interface{}{
	(*Empty)(nil),                  // 0: virsh.Empty
	(*GetCpuFeaturesResponse)(nil), // 1: virsh.GetCpuFeaturesResponse
	(*CreateVmRequest)(nil),        // 2: virsh.CreateVmRequest
	(*OkResponse)(nil),             // 3: virsh.OkResponse
	(*Vm)(nil),                     // 4: virsh.Vm
	(*GetVmByNameRequest)(nil),     // 5: virsh.GetVmByNameRequest
	(*GetAllVmsResponse)(nil),      // 6: virsh.GetAllVmsResponse
}
var file_virsh_proto_depIdxs = []int32{
	4,  // 0: virsh.GetAllVmsResponse.vms:type_name -> virsh.Vm
	0,  // 1: virsh.SlaveVirshService.GetCpuFeatures:input_type -> virsh.Empty
	2,  // 2: virsh.SlaveVirshService.CreateVm:input_type -> virsh.CreateVmRequest
	0,  // 3: virsh.SlaveVirshService.CreateLiveVM:input_type -> virsh.Empty
	0,  // 4: virsh.SlaveVirshService.MigrateVM:input_type -> virsh.Empty
	0,  // 5: virsh.SlaveVirshService.ShutdownVM:input_type -> virsh.Empty
	0,  // 6: virsh.SlaveVirshService.StartVM:input_type -> virsh.Empty
	0,  // 7: virsh.SlaveVirshService.RemoveVM:input_type -> virsh.Empty
	0,  // 8: virsh.SlaveVirshService.GetAllVms:input_type -> virsh.Empty
	5,  // 9: virsh.SlaveVirshService.GetVmByName:input_type -> virsh.GetVmByNameRequest
	1,  // 10: virsh.SlaveVirshService.GetCpuFeatures:output_type -> virsh.GetCpuFeaturesResponse
	3,  // 11: virsh.SlaveVirshService.CreateVm:output_type -> virsh.OkResponse
	3,  // 12: virsh.SlaveVirshService.CreateLiveVM:output_type -> virsh.OkResponse
	3,  // 13: virsh.SlaveVirshService.MigrateVM:output_type -> virsh.OkResponse
	3,  // 14: virsh.SlaveVirshService.ShutdownVM:output_type -> virsh.OkResponse
	3,  // 15: virsh.SlaveVirshService.StartVM:output_type -> virsh.OkResponse
	3,  // 16: virsh.SlaveVirshService.RemoveVM:output_type -> virsh.OkResponse
	6,  // 17: virsh.SlaveVirshService.GetAllVms:output_type -> virsh.GetAllVmsResponse
	4,  // 18: virsh.SlaveVirshService.GetVmByName:output_type -> virsh.Vm
	10, // [10:19] is the sub-list for method output_type
	1,  // [1:10] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_virsh_proto_init() }
func file_virsh_proto_init() {
	if File_virsh_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_virsh_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_virsh_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCpuFeaturesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_virsh_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateVmRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_virsh_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OkResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_virsh_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Vm); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_virsh_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetVmByNameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_virsh_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllVmsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_virsh_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_virsh_proto_goTypes,
		DependencyIndexes: file_virsh_proto_depIdxs,
		MessageInfos:      file_virsh_proto_msgTypes,
	}.Build()
	File_virsh_proto = out.File
	file_virsh_proto_rawDesc = nil
	file_virsh_proto_goTypes = nil
	file_virsh_proto_depIdxs = nil
}
