// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.6
// source: docker.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DockerService_ImageDownload_FullMethodName       = "/docker.DockerService/ImageDownload"
	DockerService_ImageRemove_FullMethodName         = "/docker.DockerService/ImageRemove"
	DockerService_ImageList_FullMethodName           = "/docker.DockerService/ImageList"
	DockerService_ContainerList_FullMethodName       = "/docker.DockerService/ContainerList"
	DockerService_ContainerCreateFunc_FullMethodName = "/docker.DockerService/ContainerCreateFunc"
	DockerService_ContainerRemove_FullMethodName     = "/docker.DockerService/ContainerRemove"
	DockerService_ContainerStop_FullMethodName       = "/docker.DockerService/ContainerStop"
	DockerService_ContainerStart_FullMethodName      = "/docker.DockerService/ContainerStart"
	DockerService_ContainerRestart_FullMethodName    = "/docker.DockerService/ContainerRestart"
	DockerService_ContainerPause_FullMethodName      = "/docker.DockerService/ContainerPause"
	DockerService_ContainerUnPause_FullMethodName    = "/docker.DockerService/ContainerUnPause"
	DockerService_ContainerKill_FullMethodName       = "/docker.DockerService/ContainerKill"
)

// DockerServiceClient is the client API for DockerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DockerServiceClient interface {
	ImageDownload(ctx context.Context, in *DownloadImage, opts ...grpc.CallOption) (*Empty, error)
	ImageRemove(ctx context.Context, in *Remove, opts ...grpc.CallOption) (*Empty, error)
	ImageList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListOfImages, error)
	ContainerList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListOfContainers, error)
	ContainerCreateFunc(ctx context.Context, in *ContainerCreate, opts ...grpc.CallOption) (*Empty, error)
	ContainerRemove(ctx context.Context, in *RemoveContainer, opts ...grpc.CallOption) (*Empty, error)
	ContainerStop(ctx context.Context, in *ContainerId, opts ...grpc.CallOption) (*Empty, error)
	ContainerStart(ctx context.Context, in *ContainerId, opts ...grpc.CallOption) (*Empty, error)
	ContainerRestart(ctx context.Context, in *ContainerId, opts ...grpc.CallOption) (*Empty, error)
	ContainerPause(ctx context.Context, in *ContainerId, opts ...grpc.CallOption) (*Empty, error)
	ContainerUnPause(ctx context.Context, in *ContainerId, opts ...grpc.CallOption) (*Empty, error)
	ContainerKill(ctx context.Context, in *KillContainer, opts ...grpc.CallOption) (*Empty, error)
}

type dockerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDockerServiceClient(cc grpc.ClientConnInterface) DockerServiceClient {
	return &dockerServiceClient{cc}
}

func (c *dockerServiceClient) ImageDownload(ctx context.Context, in *DownloadImage, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, DockerService_ImageDownload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dockerServiceClient) ImageRemove(ctx context.Context, in *Remove, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, DockerService_ImageRemove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dockerServiceClient) ImageList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListOfImages, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListOfImages)
	err := c.cc.Invoke(ctx, DockerService_ImageList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dockerServiceClient) ContainerList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListOfContainers, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListOfContainers)
	err := c.cc.Invoke(ctx, DockerService_ContainerList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dockerServiceClient) ContainerCreateFunc(ctx context.Context, in *ContainerCreate, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, DockerService_ContainerCreateFunc_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dockerServiceClient) ContainerRemove(ctx context.Context, in *RemoveContainer, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, DockerService_ContainerRemove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dockerServiceClient) ContainerStop(ctx context.Context, in *ContainerId, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, DockerService_ContainerStop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dockerServiceClient) ContainerStart(ctx context.Context, in *ContainerId, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, DockerService_ContainerStart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dockerServiceClient) ContainerRestart(ctx context.Context, in *ContainerId, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, DockerService_ContainerRestart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dockerServiceClient) ContainerPause(ctx context.Context, in *ContainerId, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, DockerService_ContainerPause_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dockerServiceClient) ContainerUnPause(ctx context.Context, in *ContainerId, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, DockerService_ContainerUnPause_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dockerServiceClient) ContainerKill(ctx context.Context, in *KillContainer, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, DockerService_ContainerKill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DockerServiceServer is the server API for DockerService service.
// All implementations must embed UnimplementedDockerServiceServer
// for forward compatibility.
type DockerServiceServer interface {
	ImageDownload(context.Context, *DownloadImage) (*Empty, error)
	ImageRemove(context.Context, *Remove) (*Empty, error)
	ImageList(context.Context, *Empty) (*ListOfImages, error)
	ContainerList(context.Context, *Empty) (*ListOfContainers, error)
	ContainerCreateFunc(context.Context, *ContainerCreate) (*Empty, error)
	ContainerRemove(context.Context, *RemoveContainer) (*Empty, error)
	ContainerStop(context.Context, *ContainerId) (*Empty, error)
	ContainerStart(context.Context, *ContainerId) (*Empty, error)
	ContainerRestart(context.Context, *ContainerId) (*Empty, error)
	ContainerPause(context.Context, *ContainerId) (*Empty, error)
	ContainerUnPause(context.Context, *ContainerId) (*Empty, error)
	ContainerKill(context.Context, *KillContainer) (*Empty, error)
	mustEmbedUnimplementedDockerServiceServer()
}

// UnimplementedDockerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDockerServiceServer struct{}

func (UnimplementedDockerServiceServer) ImageDownload(context.Context, *DownloadImage) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ImageDownload not implemented")
}
func (UnimplementedDockerServiceServer) ImageRemove(context.Context, *Remove) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ImageRemove not implemented")
}
func (UnimplementedDockerServiceServer) ImageList(context.Context, *Empty) (*ListOfImages, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ImageList not implemented")
}
func (UnimplementedDockerServiceServer) ContainerList(context.Context, *Empty) (*ListOfContainers, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ContainerList not implemented")
}
func (UnimplementedDockerServiceServer) ContainerCreateFunc(context.Context, *ContainerCreate) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ContainerCreateFunc not implemented")
}
func (UnimplementedDockerServiceServer) ContainerRemove(context.Context, *RemoveContainer) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ContainerRemove not implemented")
}
func (UnimplementedDockerServiceServer) ContainerStop(context.Context, *ContainerId) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ContainerStop not implemented")
}
func (UnimplementedDockerServiceServer) ContainerStart(context.Context, *ContainerId) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ContainerStart not implemented")
}
func (UnimplementedDockerServiceServer) ContainerRestart(context.Context, *ContainerId) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ContainerRestart not implemented")
}
func (UnimplementedDockerServiceServer) ContainerPause(context.Context, *ContainerId) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ContainerPause not implemented")
}
func (UnimplementedDockerServiceServer) ContainerUnPause(context.Context, *ContainerId) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ContainerUnPause not implemented")
}
func (UnimplementedDockerServiceServer) ContainerKill(context.Context, *KillContainer) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ContainerKill not implemented")
}
func (UnimplementedDockerServiceServer) mustEmbedUnimplementedDockerServiceServer() {}
func (UnimplementedDockerServiceServer) testEmbeddedByValue()                       {}

// UnsafeDockerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DockerServiceServer will
// result in compilation errors.
type UnsafeDockerServiceServer interface {
	mustEmbedUnimplementedDockerServiceServer()
}

func RegisterDockerServiceServer(s grpc.ServiceRegistrar, srv DockerServiceServer) {
	// If the following call pancis, it indicates UnimplementedDockerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DockerService_ServiceDesc, srv)
}

func _DockerService_ImageDownload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownloadImage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DockerServiceServer).ImageDownload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DockerService_ImageDownload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DockerServiceServer).ImageDownload(ctx, req.(*DownloadImage))
	}
	return interceptor(ctx, in, info, handler)
}

func _DockerService_ImageRemove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Remove)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DockerServiceServer).ImageRemove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DockerService_ImageRemove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DockerServiceServer).ImageRemove(ctx, req.(*Remove))
	}
	return interceptor(ctx, in, info, handler)
}

func _DockerService_ImageList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DockerServiceServer).ImageList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DockerService_ImageList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DockerServiceServer).ImageList(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DockerService_ContainerList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DockerServiceServer).ContainerList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DockerService_ContainerList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DockerServiceServer).ContainerList(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DockerService_ContainerCreateFunc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContainerCreate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DockerServiceServer).ContainerCreateFunc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DockerService_ContainerCreateFunc_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DockerServiceServer).ContainerCreateFunc(ctx, req.(*ContainerCreate))
	}
	return interceptor(ctx, in, info, handler)
}

func _DockerService_ContainerRemove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveContainer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DockerServiceServer).ContainerRemove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DockerService_ContainerRemove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DockerServiceServer).ContainerRemove(ctx, req.(*RemoveContainer))
	}
	return interceptor(ctx, in, info, handler)
}

func _DockerService_ContainerStop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContainerId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DockerServiceServer).ContainerStop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DockerService_ContainerStop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DockerServiceServer).ContainerStop(ctx, req.(*ContainerId))
	}
	return interceptor(ctx, in, info, handler)
}

func _DockerService_ContainerStart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContainerId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DockerServiceServer).ContainerStart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DockerService_ContainerStart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DockerServiceServer).ContainerStart(ctx, req.(*ContainerId))
	}
	return interceptor(ctx, in, info, handler)
}

func _DockerService_ContainerRestart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContainerId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DockerServiceServer).ContainerRestart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DockerService_ContainerRestart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DockerServiceServer).ContainerRestart(ctx, req.(*ContainerId))
	}
	return interceptor(ctx, in, info, handler)
}

func _DockerService_ContainerPause_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContainerId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DockerServiceServer).ContainerPause(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DockerService_ContainerPause_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DockerServiceServer).ContainerPause(ctx, req.(*ContainerId))
	}
	return interceptor(ctx, in, info, handler)
}

func _DockerService_ContainerUnPause_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContainerId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DockerServiceServer).ContainerUnPause(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DockerService_ContainerUnPause_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DockerServiceServer).ContainerUnPause(ctx, req.(*ContainerId))
	}
	return interceptor(ctx, in, info, handler)
}

func _DockerService_ContainerKill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KillContainer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DockerServiceServer).ContainerKill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DockerService_ContainerKill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DockerServiceServer).ContainerKill(ctx, req.(*KillContainer))
	}
	return interceptor(ctx, in, info, handler)
}

// DockerService_ServiceDesc is the grpc.ServiceDesc for DockerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DockerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "docker.DockerService",
	HandlerType: (*DockerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ImageDownload",
			Handler:    _DockerService_ImageDownload_Handler,
		},
		{
			MethodName: "ImageRemove",
			Handler:    _DockerService_ImageRemove_Handler,
		},
		{
			MethodName: "ImageList",
			Handler:    _DockerService_ImageList_Handler,
		},
		{
			MethodName: "ContainerList",
			Handler:    _DockerService_ContainerList_Handler,
		},
		{
			MethodName: "ContainerCreateFunc",
			Handler:    _DockerService_ContainerCreateFunc_Handler,
		},
		{
			MethodName: "ContainerRemove",
			Handler:    _DockerService_ContainerRemove_Handler,
		},
		{
			MethodName: "ContainerStop",
			Handler:    _DockerService_ContainerStop_Handler,
		},
		{
			MethodName: "ContainerStart",
			Handler:    _DockerService_ContainerStart_Handler,
		},
		{
			MethodName: "ContainerRestart",
			Handler:    _DockerService_ContainerRestart_Handler,
		},
		{
			MethodName: "ContainerPause",
			Handler:    _DockerService_ContainerPause_Handler,
		},
		{
			MethodName: "ContainerUnPause",
			Handler:    _DockerService_ContainerUnPause_Handler,
		},
		{
			MethodName: "ContainerKill",
			Handler:    _DockerService_ContainerKill_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "docker.proto",
}
