// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.6
// source: docker.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DockerService_ImageDownload_FullMethodName         = "/docker.DockerService/ImageDownload"
	DockerService_ImageRemove_FullMethodName           = "/docker.DockerService/ImageRemove"
	DockerService_ImageList_FullMethodName             = "/docker.DockerService/ImageList"
	DockerService_ContainerList_FullMethodName         = "/docker.DockerService/ContainerList"
	DockerService_ContainerCreateFunc_FullMethodName   = "/docker.DockerService/ContainerCreateFunc"
	DockerService_ContainerRemove_FullMethodName       = "/docker.DockerService/ContainerRemove"
	DockerService_ContainerStop_FullMethodName         = "/docker.DockerService/ContainerStop"
	DockerService_ContainerStart_FullMethodName        = "/docker.DockerService/ContainerStart"
	DockerService_ContainerRestart_FullMethodName      = "/docker.DockerService/ContainerRestart"
	DockerService_ContainerPause_FullMethodName        = "/docker.DockerService/ContainerPause"
	DockerService_ContainerUnPause_FullMethodName      = "/docker.DockerService/ContainerUnPause"
	DockerService_ContainerKill_FullMethodName         = "/docker.DockerService/ContainerKill"
	DockerService_ContainerLogs_FullMethodName         = "/docker.DockerService/ContainerLogs"
	DockerService_ContainerUpdate_FullMethodName       = "/docker.DockerService/ContainerUpdate"
	DockerService_ContainerRename_FullMethodName       = "/docker.DockerService/ContainerRename"
	DockerService_ContainerExec_FullMethodName         = "/docker.DockerService/ContainerExec"
	DockerService_VolumeList_FullMethodName            = "/docker.DockerService/VolumeList"
	DockerService_VolumeCreateBindMount_FullMethodName = "/docker.DockerService/VolumeCreateBindMount"
	DockerService_VolumeRemove_FullMethodName          = "/docker.DockerService/VolumeRemove"
	DockerService_NetworkCreate_FullMethodName         = "/docker.DockerService/NetworkCreate"
	DockerService_NetworkRemove_FullMethodName         = "/docker.DockerService/NetworkRemove"
	DockerService_NetworkList_FullMethodName           = "/docker.DockerService/NetworkList"
	DockerService_GitClone_FullMethodName              = "/docker.DockerService/GitClone"
	DockerService_GitList_FullMethodName               = "/docker.DockerService/GitList"
	DockerService_GitRemove_FullMethodName             = "/docker.DockerService/GitRemove"
	DockerService_GitUpdate_FullMethodName             = "/docker.DockerService/GitUpdate"
)

// DockerServiceClient is the client API for DockerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DockerServiceClient interface {
	ImageDownload(ctx context.Context, in *DownloadImage, opts ...grpc.CallOption) (*Empty, error)
	ImageRemove(ctx context.Context, in *Remove, opts ...grpc.CallOption) (*Empty, error)
	ImageList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListOfImages, error)
	// Containers :D:D:D IUUUPIIIIIIIIIIII
	ContainerList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListOfContainers, error)
	ContainerCreateFunc(ctx context.Context, in *ContainerCreate, opts ...grpc.CallOption) (*Empty, error)
	ContainerRemove(ctx context.Context, in *RemoveContainer, opts ...grpc.CallOption) (*Empty, error)
	ContainerStop(ctx context.Context, in *ContainerId, opts ...grpc.CallOption) (*Empty, error)
	ContainerStart(ctx context.Context, in *ContainerId, opts ...grpc.CallOption) (*Empty, error)
	ContainerRestart(ctx context.Context, in *ContainerId, opts ...grpc.CallOption) (*Empty, error)
	ContainerPause(ctx context.Context, in *ContainerId, opts ...grpc.CallOption) (*Empty, error)
	ContainerUnPause(ctx context.Context, in *ContainerId, opts ...grpc.CallOption) (*Empty, error)
	ContainerKill(ctx context.Context, in *KillContainer, opts ...grpc.CallOption) (*Empty, error)
	ContainerLogs(ctx context.Context, in *ContainerLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogChunk], error)
	ContainerUpdate(ctx context.Context, in *ContainerUpdateRequest, opts ...grpc.CallOption) (*ContainerUpdateResponse, error)
	ContainerRename(ctx context.Context, in *ContainerRenameRequest, opts ...grpc.CallOption) (*Empty, error)
	ContainerExec(ctx context.Context, in *ExecMsg, opts ...grpc.CallOption) (*Empty, error)
	// Volumes pa puder juntar po novo super mariooooo
	// eu fico por baixo ela ...
	VolumeList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListVolumesResponse, error)
	VolumeCreateBindMount(ctx context.Context, in *VolumeCreateRequest, opts ...grpc.CallOption) (*Empty, error)
	VolumeRemove(ctx context.Context, in *VolumeRemoveRequest, opts ...grpc.CallOption) (*Empty, error)
	// Networks
	NetworkCreate(ctx context.Context, in *NetworkCreateRequest, opts ...grpc.CallOption) (*Empty, error)
	NetworkRemove(ctx context.Context, in *NetworkRemoveRequest, opts ...grpc.CallOption) (*Empty, error)
	NetworkList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NetworkListResponse, error)
	// git compose
	GitClone(ctx context.Context, in *GitCloneReq, opts ...grpc.CallOption) (*Empty, error)
	GitList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GitListReq, error)
	GitRemove(ctx context.Context, in *GitRemoveReq, opts ...grpc.CallOption) (*Empty, error)
	GitUpdate(ctx context.Context, in *GitUpdateReq, opts ...grpc.CallOption) (*Empty, error)
}

type dockerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDockerServiceClient(cc grpc.ClientConnInterface) DockerServiceClient {
	return &dockerServiceClient{cc}
}

func (c *dockerServiceClient) ImageDownload(ctx context.Context, in *DownloadImage, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, DockerService_ImageDownload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dockerServiceClient) ImageRemove(ctx context.Context, in *Remove, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, DockerService_ImageRemove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dockerServiceClient) ImageList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListOfImages, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListOfImages)
	err := c.cc.Invoke(ctx, DockerService_ImageList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dockerServiceClient) ContainerList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListOfContainers, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListOfContainers)
	err := c.cc.Invoke(ctx, DockerService_ContainerList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dockerServiceClient) ContainerCreateFunc(ctx context.Context, in *ContainerCreate, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, DockerService_ContainerCreateFunc_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dockerServiceClient) ContainerRemove(ctx context.Context, in *RemoveContainer, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, DockerService_ContainerRemove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dockerServiceClient) ContainerStop(ctx context.Context, in *ContainerId, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, DockerService_ContainerStop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dockerServiceClient) ContainerStart(ctx context.Context, in *ContainerId, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, DockerService_ContainerStart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dockerServiceClient) ContainerRestart(ctx context.Context, in *ContainerId, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, DockerService_ContainerRestart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dockerServiceClient) ContainerPause(ctx context.Context, in *ContainerId, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, DockerService_ContainerPause_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dockerServiceClient) ContainerUnPause(ctx context.Context, in *ContainerId, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, DockerService_ContainerUnPause_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dockerServiceClient) ContainerKill(ctx context.Context, in *KillContainer, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, DockerService_ContainerKill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dockerServiceClient) ContainerLogs(ctx context.Context, in *ContainerLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DockerService_ServiceDesc.Streams[0], DockerService_ContainerLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ContainerLogsRequest, LogChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DockerService_ContainerLogsClient = grpc.ServerStreamingClient[LogChunk]

func (c *dockerServiceClient) ContainerUpdate(ctx context.Context, in *ContainerUpdateRequest, opts ...grpc.CallOption) (*ContainerUpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContainerUpdateResponse)
	err := c.cc.Invoke(ctx, DockerService_ContainerUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dockerServiceClient) ContainerRename(ctx context.Context, in *ContainerRenameRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, DockerService_ContainerRename_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dockerServiceClient) ContainerExec(ctx context.Context, in *ExecMsg, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, DockerService_ContainerExec_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dockerServiceClient) VolumeList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListVolumesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListVolumesResponse)
	err := c.cc.Invoke(ctx, DockerService_VolumeList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dockerServiceClient) VolumeCreateBindMount(ctx context.Context, in *VolumeCreateRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, DockerService_VolumeCreateBindMount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dockerServiceClient) VolumeRemove(ctx context.Context, in *VolumeRemoveRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, DockerService_VolumeRemove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dockerServiceClient) NetworkCreate(ctx context.Context, in *NetworkCreateRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, DockerService_NetworkCreate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dockerServiceClient) NetworkRemove(ctx context.Context, in *NetworkRemoveRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, DockerService_NetworkRemove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dockerServiceClient) NetworkList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NetworkListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NetworkListResponse)
	err := c.cc.Invoke(ctx, DockerService_NetworkList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dockerServiceClient) GitClone(ctx context.Context, in *GitCloneReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, DockerService_GitClone_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dockerServiceClient) GitList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GitListReq, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GitListReq)
	err := c.cc.Invoke(ctx, DockerService_GitList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dockerServiceClient) GitRemove(ctx context.Context, in *GitRemoveReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, DockerService_GitRemove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dockerServiceClient) GitUpdate(ctx context.Context, in *GitUpdateReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, DockerService_GitUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DockerServiceServer is the server API for DockerService service.
// All implementations must embed UnimplementedDockerServiceServer
// for forward compatibility.
type DockerServiceServer interface {
	ImageDownload(context.Context, *DownloadImage) (*Empty, error)
	ImageRemove(context.Context, *Remove) (*Empty, error)
	ImageList(context.Context, *Empty) (*ListOfImages, error)
	// Containers :D:D:D IUUUPIIIIIIIIIIII
	ContainerList(context.Context, *Empty) (*ListOfContainers, error)
	ContainerCreateFunc(context.Context, *ContainerCreate) (*Empty, error)
	ContainerRemove(context.Context, *RemoveContainer) (*Empty, error)
	ContainerStop(context.Context, *ContainerId) (*Empty, error)
	ContainerStart(context.Context, *ContainerId) (*Empty, error)
	ContainerRestart(context.Context, *ContainerId) (*Empty, error)
	ContainerPause(context.Context, *ContainerId) (*Empty, error)
	ContainerUnPause(context.Context, *ContainerId) (*Empty, error)
	ContainerKill(context.Context, *KillContainer) (*Empty, error)
	ContainerLogs(*ContainerLogsRequest, grpc.ServerStreamingServer[LogChunk]) error
	ContainerUpdate(context.Context, *ContainerUpdateRequest) (*ContainerUpdateResponse, error)
	ContainerRename(context.Context, *ContainerRenameRequest) (*Empty, error)
	ContainerExec(context.Context, *ExecMsg) (*Empty, error)
	// Volumes pa puder juntar po novo super mariooooo
	// eu fico por baixo ela ...
	VolumeList(context.Context, *Empty) (*ListVolumesResponse, error)
	VolumeCreateBindMount(context.Context, *VolumeCreateRequest) (*Empty, error)
	VolumeRemove(context.Context, *VolumeRemoveRequest) (*Empty, error)
	// Networks
	NetworkCreate(context.Context, *NetworkCreateRequest) (*Empty, error)
	NetworkRemove(context.Context, *NetworkRemoveRequest) (*Empty, error)
	NetworkList(context.Context, *Empty) (*NetworkListResponse, error)
	// git compose
	GitClone(context.Context, *GitCloneReq) (*Empty, error)
	GitList(context.Context, *Empty) (*GitListReq, error)
	GitRemove(context.Context, *GitRemoveReq) (*Empty, error)
	GitUpdate(context.Context, *GitUpdateReq) (*Empty, error)
	mustEmbedUnimplementedDockerServiceServer()
}

// UnimplementedDockerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDockerServiceServer struct{}

func (UnimplementedDockerServiceServer) ImageDownload(context.Context, *DownloadImage) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ImageDownload not implemented")
}
func (UnimplementedDockerServiceServer) ImageRemove(context.Context, *Remove) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ImageRemove not implemented")
}
func (UnimplementedDockerServiceServer) ImageList(context.Context, *Empty) (*ListOfImages, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ImageList not implemented")
}
func (UnimplementedDockerServiceServer) ContainerList(context.Context, *Empty) (*ListOfContainers, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ContainerList not implemented")
}
func (UnimplementedDockerServiceServer) ContainerCreateFunc(context.Context, *ContainerCreate) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ContainerCreateFunc not implemented")
}
func (UnimplementedDockerServiceServer) ContainerRemove(context.Context, *RemoveContainer) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ContainerRemove not implemented")
}
func (UnimplementedDockerServiceServer) ContainerStop(context.Context, *ContainerId) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ContainerStop not implemented")
}
func (UnimplementedDockerServiceServer) ContainerStart(context.Context, *ContainerId) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ContainerStart not implemented")
}
func (UnimplementedDockerServiceServer) ContainerRestart(context.Context, *ContainerId) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ContainerRestart not implemented")
}
func (UnimplementedDockerServiceServer) ContainerPause(context.Context, *ContainerId) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ContainerPause not implemented")
}
func (UnimplementedDockerServiceServer) ContainerUnPause(context.Context, *ContainerId) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ContainerUnPause not implemented")
}
func (UnimplementedDockerServiceServer) ContainerKill(context.Context, *KillContainer) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ContainerKill not implemented")
}
func (UnimplementedDockerServiceServer) ContainerLogs(*ContainerLogsRequest, grpc.ServerStreamingServer[LogChunk]) error {
	return status.Errorf(codes.Unimplemented, "method ContainerLogs not implemented")
}
func (UnimplementedDockerServiceServer) ContainerUpdate(context.Context, *ContainerUpdateRequest) (*ContainerUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ContainerUpdate not implemented")
}
func (UnimplementedDockerServiceServer) ContainerRename(context.Context, *ContainerRenameRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ContainerRename not implemented")
}
func (UnimplementedDockerServiceServer) ContainerExec(context.Context, *ExecMsg) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ContainerExec not implemented")
}
func (UnimplementedDockerServiceServer) VolumeList(context.Context, *Empty) (*ListVolumesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VolumeList not implemented")
}
func (UnimplementedDockerServiceServer) VolumeCreateBindMount(context.Context, *VolumeCreateRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VolumeCreateBindMount not implemented")
}
func (UnimplementedDockerServiceServer) VolumeRemove(context.Context, *VolumeRemoveRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VolumeRemove not implemented")
}
func (UnimplementedDockerServiceServer) NetworkCreate(context.Context, *NetworkCreateRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NetworkCreate not implemented")
}
func (UnimplementedDockerServiceServer) NetworkRemove(context.Context, *NetworkRemoveRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NetworkRemove not implemented")
}
func (UnimplementedDockerServiceServer) NetworkList(context.Context, *Empty) (*NetworkListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NetworkList not implemented")
}
func (UnimplementedDockerServiceServer) GitClone(context.Context, *GitCloneReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GitClone not implemented")
}
func (UnimplementedDockerServiceServer) GitList(context.Context, *Empty) (*GitListReq, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GitList not implemented")
}
func (UnimplementedDockerServiceServer) GitRemove(context.Context, *GitRemoveReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GitRemove not implemented")
}
func (UnimplementedDockerServiceServer) GitUpdate(context.Context, *GitUpdateReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GitUpdate not implemented")
}
func (UnimplementedDockerServiceServer) mustEmbedUnimplementedDockerServiceServer() {}
func (UnimplementedDockerServiceServer) testEmbeddedByValue()                       {}

// UnsafeDockerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DockerServiceServer will
// result in compilation errors.
type UnsafeDockerServiceServer interface {
	mustEmbedUnimplementedDockerServiceServer()
}

func RegisterDockerServiceServer(s grpc.ServiceRegistrar, srv DockerServiceServer) {
	// If the following call pancis, it indicates UnimplementedDockerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DockerService_ServiceDesc, srv)
}

func _DockerService_ImageDownload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownloadImage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DockerServiceServer).ImageDownload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DockerService_ImageDownload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DockerServiceServer).ImageDownload(ctx, req.(*DownloadImage))
	}
	return interceptor(ctx, in, info, handler)
}

func _DockerService_ImageRemove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Remove)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DockerServiceServer).ImageRemove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DockerService_ImageRemove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DockerServiceServer).ImageRemove(ctx, req.(*Remove))
	}
	return interceptor(ctx, in, info, handler)
}

func _DockerService_ImageList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DockerServiceServer).ImageList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DockerService_ImageList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DockerServiceServer).ImageList(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DockerService_ContainerList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DockerServiceServer).ContainerList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DockerService_ContainerList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DockerServiceServer).ContainerList(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DockerService_ContainerCreateFunc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContainerCreate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DockerServiceServer).ContainerCreateFunc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DockerService_ContainerCreateFunc_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DockerServiceServer).ContainerCreateFunc(ctx, req.(*ContainerCreate))
	}
	return interceptor(ctx, in, info, handler)
}

func _DockerService_ContainerRemove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveContainer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DockerServiceServer).ContainerRemove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DockerService_ContainerRemove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DockerServiceServer).ContainerRemove(ctx, req.(*RemoveContainer))
	}
	return interceptor(ctx, in, info, handler)
}

func _DockerService_ContainerStop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContainerId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DockerServiceServer).ContainerStop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DockerService_ContainerStop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DockerServiceServer).ContainerStop(ctx, req.(*ContainerId))
	}
	return interceptor(ctx, in, info, handler)
}

func _DockerService_ContainerStart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContainerId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DockerServiceServer).ContainerStart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DockerService_ContainerStart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DockerServiceServer).ContainerStart(ctx, req.(*ContainerId))
	}
	return interceptor(ctx, in, info, handler)
}

func _DockerService_ContainerRestart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContainerId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DockerServiceServer).ContainerRestart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DockerService_ContainerRestart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DockerServiceServer).ContainerRestart(ctx, req.(*ContainerId))
	}
	return interceptor(ctx, in, info, handler)
}

func _DockerService_ContainerPause_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContainerId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DockerServiceServer).ContainerPause(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DockerService_ContainerPause_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DockerServiceServer).ContainerPause(ctx, req.(*ContainerId))
	}
	return interceptor(ctx, in, info, handler)
}

func _DockerService_ContainerUnPause_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContainerId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DockerServiceServer).ContainerUnPause(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DockerService_ContainerUnPause_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DockerServiceServer).ContainerUnPause(ctx, req.(*ContainerId))
	}
	return interceptor(ctx, in, info, handler)
}

func _DockerService_ContainerKill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KillContainer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DockerServiceServer).ContainerKill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DockerService_ContainerKill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DockerServiceServer).ContainerKill(ctx, req.(*KillContainer))
	}
	return interceptor(ctx, in, info, handler)
}

func _DockerService_ContainerLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ContainerLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DockerServiceServer).ContainerLogs(m, &grpc.GenericServerStream[ContainerLogsRequest, LogChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DockerService_ContainerLogsServer = grpc.ServerStreamingServer[LogChunk]

func _DockerService_ContainerUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContainerUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DockerServiceServer).ContainerUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DockerService_ContainerUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DockerServiceServer).ContainerUpdate(ctx, req.(*ContainerUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DockerService_ContainerRename_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContainerRenameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DockerServiceServer).ContainerRename(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DockerService_ContainerRename_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DockerServiceServer).ContainerRename(ctx, req.(*ContainerRenameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DockerService_ContainerExec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DockerServiceServer).ContainerExec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DockerService_ContainerExec_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DockerServiceServer).ContainerExec(ctx, req.(*ExecMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _DockerService_VolumeList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DockerServiceServer).VolumeList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DockerService_VolumeList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DockerServiceServer).VolumeList(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DockerService_VolumeCreateBindMount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VolumeCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DockerServiceServer).VolumeCreateBindMount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DockerService_VolumeCreateBindMount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DockerServiceServer).VolumeCreateBindMount(ctx, req.(*VolumeCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DockerService_VolumeRemove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VolumeRemoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DockerServiceServer).VolumeRemove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DockerService_VolumeRemove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DockerServiceServer).VolumeRemove(ctx, req.(*VolumeRemoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DockerService_NetworkCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NetworkCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DockerServiceServer).NetworkCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DockerService_NetworkCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DockerServiceServer).NetworkCreate(ctx, req.(*NetworkCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DockerService_NetworkRemove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NetworkRemoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DockerServiceServer).NetworkRemove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DockerService_NetworkRemove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DockerServiceServer).NetworkRemove(ctx, req.(*NetworkRemoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DockerService_NetworkList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DockerServiceServer).NetworkList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DockerService_NetworkList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DockerServiceServer).NetworkList(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DockerService_GitClone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GitCloneReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DockerServiceServer).GitClone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DockerService_GitClone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DockerServiceServer).GitClone(ctx, req.(*GitCloneReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DockerService_GitList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DockerServiceServer).GitList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DockerService_GitList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DockerServiceServer).GitList(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DockerService_GitRemove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GitRemoveReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DockerServiceServer).GitRemove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DockerService_GitRemove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DockerServiceServer).GitRemove(ctx, req.(*GitRemoveReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DockerService_GitUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GitUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DockerServiceServer).GitUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DockerService_GitUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DockerServiceServer).GitUpdate(ctx, req.(*GitUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

// DockerService_ServiceDesc is the grpc.ServiceDesc for DockerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DockerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "docker.DockerService",
	HandlerType: (*DockerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ImageDownload",
			Handler:    _DockerService_ImageDownload_Handler,
		},
		{
			MethodName: "ImageRemove",
			Handler:    _DockerService_ImageRemove_Handler,
		},
		{
			MethodName: "ImageList",
			Handler:    _DockerService_ImageList_Handler,
		},
		{
			MethodName: "ContainerList",
			Handler:    _DockerService_ContainerList_Handler,
		},
		{
			MethodName: "ContainerCreateFunc",
			Handler:    _DockerService_ContainerCreateFunc_Handler,
		},
		{
			MethodName: "ContainerRemove",
			Handler:    _DockerService_ContainerRemove_Handler,
		},
		{
			MethodName: "ContainerStop",
			Handler:    _DockerService_ContainerStop_Handler,
		},
		{
			MethodName: "ContainerStart",
			Handler:    _DockerService_ContainerStart_Handler,
		},
		{
			MethodName: "ContainerRestart",
			Handler:    _DockerService_ContainerRestart_Handler,
		},
		{
			MethodName: "ContainerPause",
			Handler:    _DockerService_ContainerPause_Handler,
		},
		{
			MethodName: "ContainerUnPause",
			Handler:    _DockerService_ContainerUnPause_Handler,
		},
		{
			MethodName: "ContainerKill",
			Handler:    _DockerService_ContainerKill_Handler,
		},
		{
			MethodName: "ContainerUpdate",
			Handler:    _DockerService_ContainerUpdate_Handler,
		},
		{
			MethodName: "ContainerRename",
			Handler:    _DockerService_ContainerRename_Handler,
		},
		{
			MethodName: "ContainerExec",
			Handler:    _DockerService_ContainerExec_Handler,
		},
		{
			MethodName: "VolumeList",
			Handler:    _DockerService_VolumeList_Handler,
		},
		{
			MethodName: "VolumeCreateBindMount",
			Handler:    _DockerService_VolumeCreateBindMount_Handler,
		},
		{
			MethodName: "VolumeRemove",
			Handler:    _DockerService_VolumeRemove_Handler,
		},
		{
			MethodName: "NetworkCreate",
			Handler:    _DockerService_NetworkCreate_Handler,
		},
		{
			MethodName: "NetworkRemove",
			Handler:    _DockerService_NetworkRemove_Handler,
		},
		{
			MethodName: "NetworkList",
			Handler:    _DockerService_NetworkList_Handler,
		},
		{
			MethodName: "GitClone",
			Handler:    _DockerService_GitClone_Handler,
		},
		{
			MethodName: "GitList",
			Handler:    _DockerService_GitList_Handler,
		},
		{
			MethodName: "GitRemove",
			Handler:    _DockerService_GitRemove_Handler,
		},
		{
			MethodName: "GitUpdate",
			Handler:    _DockerService_GitUpdate_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ContainerLogs",
			Handler:       _DockerService_ContainerLogs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "docker.proto",
}
