// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.19.6
// source: btrfs.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MinDisk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Mounted       bool                   `protobuf:"varint,2,opt,name=mounted,proto3" json:"mounted,omitempty"`
	SizeGb        float64                `protobuf:"fixed64,3,opt,name=size_gb,json=sizeGb,proto3" json:"size_gb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MinDisk) Reset() {
	*x = MinDisk{}
	mi := &file_btrfs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MinDisk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MinDisk) ProtoMessage() {}

func (x *MinDisk) ProtoReflect() protoreflect.Message {
	mi := &file_btrfs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MinDisk.ProtoReflect.Descriptor instead.
func (*MinDisk) Descriptor() ([]byte, []int) {
	return file_btrfs_proto_rawDescGZIP(), []int{0}
}

func (x *MinDisk) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *MinDisk) GetMounted() bool {
	if x != nil {
		return x.Mounted
	}
	return false
}

func (x *MinDisk) GetSizeGb() float64 {
	if x != nil {
		return x.SizeGb
	}
	return 0
}

type MinDiskArr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Disks         []*MinDisk             `protobuf:"bytes,1,rep,name=disks,proto3" json:"disks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MinDiskArr) Reset() {
	*x = MinDiskArr{}
	mi := &file_btrfs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MinDiskArr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MinDiskArr) ProtoMessage() {}

func (x *MinDiskArr) ProtoReflect() protoreflect.Message {
	mi := &file_btrfs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MinDiskArr.ProtoReflect.Descriptor instead.
func (*MinDiskArr) Descriptor() ([]byte, []int) {
	return file_btrfs_proto_rawDescGZIP(), []int{1}
}

func (x *MinDiskArr) GetDisks() []*MinDisk {
	if x != nil {
		return x.Disks
	}
	return nil
}

type BtrfsDevice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Label         string                 `protobuf:"bytes,4,opt,name=label,proto3" json:"label,omitempty"`
	Uuid          string                 `protobuf:"bytes,5,opt,name=uuid,proto3" json:"uuid,omitempty"`
	UuidSub       string                 `protobuf:"bytes,6,opt,name=uuid_sub,json=uuidSub,proto3" json:"uuid_sub,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,7,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	MountPoint    string                 `protobuf:"bytes,8,opt,name=mount_point,json=mountPoint,proto3" json:"mount_point,omitempty"`
	Mounted       bool                   `protobuf:"varint,9,opt,name=mounted,proto3" json:"mounted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BtrfsDevice) Reset() {
	*x = BtrfsDevice{}
	mi := &file_btrfs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BtrfsDevice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BtrfsDevice) ProtoMessage() {}

func (x *BtrfsDevice) ProtoReflect() protoreflect.Message {
	mi := &file_btrfs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BtrfsDevice.ProtoReflect.Descriptor instead.
func (*BtrfsDevice) Descriptor() ([]byte, []int) {
	return file_btrfs_proto_rawDescGZIP(), []int{2}
}

func (x *BtrfsDevice) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BtrfsDevice) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *BtrfsDevice) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *BtrfsDevice) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *BtrfsDevice) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *BtrfsDevice) GetUuidSub() string {
	if x != nil {
		return x.UuidSub
	}
	return ""
}

func (x *BtrfsDevice) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *BtrfsDevice) GetMountPoint() string {
	if x != nil {
		return x.MountPoint
	}
	return ""
}

func (x *BtrfsDevice) GetMounted() bool {
	if x != nil {
		return x.Mounted
	}
	return false
}

type FileSystem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	FsType        string                 `protobuf:"bytes,3,opt,name=fs_type,json=fsType,proto3" json:"fs_type,omitempty"`
	Options       string                 `protobuf:"bytes,4,opt,name=options,proto3" json:"options,omitempty"`
	Uuid          string                 `protobuf:"bytes,5,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Label         string                 `protobuf:"bytes,6,opt,name=label,proto3" json:"label,omitempty"`
	Compression   string                 `protobuf:"bytes,7,opt,name=compression,proto3" json:"compression,omitempty"`
	MaxSpace      int64                  `protobuf:"varint,8,opt,name=max_space,json=maxSpace,proto3" json:"max_space,omitempty"`
	UsedSpace     int64                  `protobuf:"varint,9,opt,name=used_space,json=usedSpace,proto3" json:"used_space,omitempty"`
	RealMaxSpace  int64                  `protobuf:"varint,10,opt,name=real_max_space,json=realMaxSpace,proto3" json:"real_max_space,omitempty"`
	RealUsedSpace int64                  `protobuf:"varint,11,opt,name=real_used_space,json=realUsedSpace,proto3" json:"real_used_space,omitempty"`
	Devices       []*BtrfsDevice         `protobuf:"bytes,12,rep,name=devices,proto3" json:"devices,omitempty"`
	Children      []*FileSystem          `protobuf:"bytes,13,rep,name=children,proto3" json:"children,omitempty"`
	Mounted       bool                   `protobuf:"varint,14,opt,name=mounted,proto3" json:"mounted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileSystem) Reset() {
	*x = FileSystem{}
	mi := &file_btrfs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileSystem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileSystem) ProtoMessage() {}

func (x *FileSystem) ProtoReflect() protoreflect.Message {
	mi := &file_btrfs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileSystem.ProtoReflect.Descriptor instead.
func (*FileSystem) Descriptor() ([]byte, []int) {
	return file_btrfs_proto_rawDescGZIP(), []int{3}
}

func (x *FileSystem) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *FileSystem) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *FileSystem) GetFsType() string {
	if x != nil {
		return x.FsType
	}
	return ""
}

func (x *FileSystem) GetOptions() string {
	if x != nil {
		return x.Options
	}
	return ""
}

func (x *FileSystem) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *FileSystem) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *FileSystem) GetCompression() string {
	if x != nil {
		return x.Compression
	}
	return ""
}

func (x *FileSystem) GetMaxSpace() int64 {
	if x != nil {
		return x.MaxSpace
	}
	return 0
}

func (x *FileSystem) GetUsedSpace() int64 {
	if x != nil {
		return x.UsedSpace
	}
	return 0
}

func (x *FileSystem) GetRealMaxSpace() int64 {
	if x != nil {
		return x.RealMaxSpace
	}
	return 0
}

func (x *FileSystem) GetRealUsedSpace() int64 {
	if x != nil {
		return x.RealUsedSpace
	}
	return 0
}

func (x *FileSystem) GetDevices() []*BtrfsDevice {
	if x != nil {
		return x.Devices
	}
	return nil
}

func (x *FileSystem) GetChildren() []*FileSystem {
	if x != nil {
		return x.Children
	}
	return nil
}

func (x *FileSystem) GetMounted() bool {
	if x != nil {
		return x.Mounted
	}
	return false
}

type FindMntOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filesystems   []*FileSystem          `protobuf:"bytes,1,rep,name=filesystems,proto3" json:"filesystems,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindMntOutput) Reset() {
	*x = FindMntOutput{}
	mi := &file_btrfs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindMntOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindMntOutput) ProtoMessage() {}

func (x *FindMntOutput) ProtoReflect() protoreflect.Message {
	mi := &file_btrfs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindMntOutput.ProtoReflect.Descriptor instead.
func (*FindMntOutput) Descriptor() ([]byte, []int) {
	return file_btrfs_proto_rawDescGZIP(), []int{4}
}

func (x *FindMntOutput) GetFilesystems() []*FileSystem {
	if x != nil {
		return x.Filesystems
	}
	return nil
}

type CreateRaidReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Raid          string                 `protobuf:"bytes,2,opt,name=raid,proto3" json:"raid,omitempty"`
	Disks         []string               `protobuf:"bytes,3,rep,name=disks,proto3" json:"disks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRaidReq) Reset() {
	*x = CreateRaidReq{}
	mi := &file_btrfs_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRaidReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRaidReq) ProtoMessage() {}

func (x *CreateRaidReq) ProtoReflect() protoreflect.Message {
	mi := &file_btrfs_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRaidReq.ProtoReflect.Descriptor instead.
func (*CreateRaidReq) Descriptor() ([]byte, []int) {
	return file_btrfs_proto_rawDescGZIP(), []int{5}
}

func (x *CreateRaidReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRaidReq) GetRaid() string {
	if x != nil {
		return x.Raid
	}
	return ""
}

func (x *CreateRaidReq) GetDisks() []string {
	if x != nil {
		return x.Disks
	}
	return nil
}

type UUIDReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UUIDReq) Reset() {
	*x = UUIDReq{}
	mi := &file_btrfs_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UUIDReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UUIDReq) ProtoMessage() {}

func (x *UUIDReq) ProtoReflect() protoreflect.Message {
	mi := &file_btrfs_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UUIDReq.ProtoReflect.Descriptor instead.
func (*UUIDReq) Descriptor() ([]byte, []int) {
	return file_btrfs_proto_rawDescGZIP(), []int{6}
}

func (x *UUIDReq) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type MountReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Compression   string                 `protobuf:"bytes,3,opt,name=compression,proto3" json:"compression,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MountReq) Reset() {
	*x = MountReq{}
	mi := &file_btrfs_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MountReq) ProtoMessage() {}

func (x *MountReq) ProtoReflect() protoreflect.Message {
	mi := &file_btrfs_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MountReq.ProtoReflect.Descriptor instead.
func (*MountReq) Descriptor() ([]byte, []int) {
	return file_btrfs_proto_rawDescGZIP(), []int{7}
}

func (x *MountReq) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *MountReq) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *MountReq) GetCompression() string {
	if x != nil {
		return x.Compression
	}
	return ""
}

type UMountReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Force         bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UMountReq) Reset() {
	*x = UMountReq{}
	mi := &file_btrfs_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UMountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UMountReq) ProtoMessage() {}

func (x *UMountReq) ProtoReflect() protoreflect.Message {
	mi := &file_btrfs_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UMountReq.ProtoReflect.Descriptor instead.
func (*UMountReq) Descriptor() ([]byte, []int) {
	return file_btrfs_proto_rawDescGZIP(), []int{8}
}

func (x *UMountReq) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *UMountReq) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_btrfs_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_btrfs_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_btrfs_proto_rawDescGZIP(), []int{9}
}

var File_btrfs_proto protoreflect.FileDescriptor

const file_btrfs_proto_rawDesc = "" +
	"\n" +
	"\vbtrfs.proto\x12\x05btrfs\"P\n" +
	"\aMinDisk\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\amounted\x18\x02 \x01(\bR\amounted\x12\x17\n" +
	"\asize_gb\x18\x03 \x01(\x01R\x06sizeGb\"2\n" +
	"\n" +
	"MinDiskArr\x12$\n" +
	"\x05disks\x18\x01 \x03(\v2\x0e.btrfs.MinDiskR\x05disks\"\xe8\x01\n" +
	"\vBtrfsDevice\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x14\n" +
	"\x05label\x18\x04 \x01(\tR\x05label\x12\x12\n" +
	"\x04uuid\x18\x05 \x01(\tR\x04uuid\x12\x19\n" +
	"\buuid_sub\x18\x06 \x01(\tR\auuidSub\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\a \x01(\x03R\tsizeBytes\x12\x1f\n" +
	"\vmount_point\x18\b \x01(\tR\n" +
	"mountPoint\x12\x18\n" +
	"\amounted\x18\t \x01(\bR\amounted\"\xbc\x03\n" +
	"\n" +
	"FileSystem\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x17\n" +
	"\afs_type\x18\x03 \x01(\tR\x06fsType\x12\x18\n" +
	"\aoptions\x18\x04 \x01(\tR\aoptions\x12\x12\n" +
	"\x04uuid\x18\x05 \x01(\tR\x04uuid\x12\x14\n" +
	"\x05label\x18\x06 \x01(\tR\x05label\x12 \n" +
	"\vcompression\x18\a \x01(\tR\vcompression\x12\x1b\n" +
	"\tmax_space\x18\b \x01(\x03R\bmaxSpace\x12\x1d\n" +
	"\n" +
	"used_space\x18\t \x01(\x03R\tusedSpace\x12$\n" +
	"\x0ereal_max_space\x18\n" +
	" \x01(\x03R\frealMaxSpace\x12&\n" +
	"\x0freal_used_space\x18\v \x01(\x03R\rrealUsedSpace\x12,\n" +
	"\adevices\x18\f \x03(\v2\x12.btrfs.BtrfsDeviceR\adevices\x12-\n" +
	"\bchildren\x18\r \x03(\v2\x11.btrfs.FileSystemR\bchildren\x12\x18\n" +
	"\amounted\x18\x0e \x01(\bR\amounted\"D\n" +
	"\rFindMntOutput\x123\n" +
	"\vfilesystems\x18\x01 \x03(\v2\x11.btrfs.FileSystemR\vfilesystems\"M\n" +
	"\rCreateRaidReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04raid\x18\x02 \x01(\tR\x04raid\x12\x14\n" +
	"\x05disks\x18\x03 \x03(\tR\x05disks\"\x1d\n" +
	"\aUUIDReq\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"X\n" +
	"\bMountReq\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12 \n" +
	"\vcompression\x18\x03 \x01(\tR\vcompression\"5\n" +
	"\tUMountReq\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"\a\n" +
	"\x05Empty2\xaf\x02\n" +
	"\fBtrFSService\x12.\n" +
	"\vGetAllDisks\x12\f.btrfs.Empty\x1a\x11.btrfs.MinDiskArr\x127\n" +
	"\x11GetAllFileSystems\x12\f.btrfs.Empty\x1a\x14.btrfs.FindMntOutput\x120\n" +
	"\n" +
	"CreateRaid\x12\x14.btrfs.CreateRaidReq\x1a\f.btrfs.Empty\x12*\n" +
	"\n" +
	"RemoveRaid\x12\x0e.btrfs.UUIDReq\x1a\f.btrfs.Empty\x12*\n" +
	"\tMountRaid\x12\x0f.btrfs.MountReq\x1a\f.btrfs.Empty\x12,\n" +
	"\n" +
	"UMountRaid\x12\x10.btrfs.UMountReq\x1a\f.btrfs.EmptyB3Z1github.com/Maruqes/512SvMan/api/proto/btrfs;protob\x06proto3"

var (
	file_btrfs_proto_rawDescOnce sync.Once
	file_btrfs_proto_rawDescData []byte
)

func file_btrfs_proto_rawDescGZIP() []byte {
	file_btrfs_proto_rawDescOnce.Do(func() {
		file_btrfs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_btrfs_proto_rawDesc), len(file_btrfs_proto_rawDesc)))
	})
	return file_btrfs_proto_rawDescData
}

var file_btrfs_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_btrfs_proto_goTypes = []any{
	(*MinDisk)(nil),       // 0: btrfs.MinDisk
	(*MinDiskArr)(nil),    // 1: btrfs.MinDiskArr
	(*BtrfsDevice)(nil),   // 2: btrfs.BtrfsDevice
	(*FileSystem)(nil),    // 3: btrfs.FileSystem
	(*FindMntOutput)(nil), // 4: btrfs.FindMntOutput
	(*CreateRaidReq)(nil), // 5: btrfs.CreateRaidReq
	(*UUIDReq)(nil),       // 6: btrfs.UUIDReq
	(*MountReq)(nil),      // 7: btrfs.MountReq
	(*UMountReq)(nil),     // 8: btrfs.UMountReq
	(*Empty)(nil),         // 9: btrfs.Empty
}
var file_btrfs_proto_depIdxs = []int32{
	0,  // 0: btrfs.MinDiskArr.disks:type_name -> btrfs.MinDisk
	2,  // 1: btrfs.FileSystem.devices:type_name -> btrfs.BtrfsDevice
	3,  // 2: btrfs.FileSystem.children:type_name -> btrfs.FileSystem
	3,  // 3: btrfs.FindMntOutput.filesystems:type_name -> btrfs.FileSystem
	9,  // 4: btrfs.BtrFSService.GetAllDisks:input_type -> btrfs.Empty
	9,  // 5: btrfs.BtrFSService.GetAllFileSystems:input_type -> btrfs.Empty
	5,  // 6: btrfs.BtrFSService.CreateRaid:input_type -> btrfs.CreateRaidReq
	6,  // 7: btrfs.BtrFSService.RemoveRaid:input_type -> btrfs.UUIDReq
	7,  // 8: btrfs.BtrFSService.MountRaid:input_type -> btrfs.MountReq
	8,  // 9: btrfs.BtrFSService.UMountRaid:input_type -> btrfs.UMountReq
	1,  // 10: btrfs.BtrFSService.GetAllDisks:output_type -> btrfs.MinDiskArr
	4,  // 11: btrfs.BtrFSService.GetAllFileSystems:output_type -> btrfs.FindMntOutput
	9,  // 12: btrfs.BtrFSService.CreateRaid:output_type -> btrfs.Empty
	9,  // 13: btrfs.BtrFSService.RemoveRaid:output_type -> btrfs.Empty
	9,  // 14: btrfs.BtrFSService.MountRaid:output_type -> btrfs.Empty
	9,  // 15: btrfs.BtrFSService.UMountRaid:output_type -> btrfs.Empty
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_btrfs_proto_init() }
func file_btrfs_proto_init() {
	if File_btrfs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_btrfs_proto_rawDesc), len(file_btrfs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_btrfs_proto_goTypes,
		DependencyIndexes: file_btrfs_proto_depIdxs,
		MessageInfos:      file_btrfs_proto_msgTypes,
	}.Build()
	File_btrfs_proto = out.File
	file_btrfs_proto_goTypes = nil
	file_btrfs_proto_depIdxs = nil
}
