// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.19.6
// source: btrfs.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MinDisk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Mounted       bool                   `protobuf:"varint,2,opt,name=mounted,proto3" json:"mounted,omitempty"`
	SizeGb        float64                `protobuf:"fixed64,3,opt,name=size_gb,json=sizeGb,proto3" json:"size_gb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MinDisk) Reset() {
	*x = MinDisk{}
	mi := &file_btrfs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MinDisk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MinDisk) ProtoMessage() {}

func (x *MinDisk) ProtoReflect() protoreflect.Message {
	mi := &file_btrfs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MinDisk.ProtoReflect.Descriptor instead.
func (*MinDisk) Descriptor() ([]byte, []int) {
	return file_btrfs_proto_rawDescGZIP(), []int{0}
}

func (x *MinDisk) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *MinDisk) GetMounted() bool {
	if x != nil {
		return x.Mounted
	}
	return false
}

func (x *MinDisk) GetSizeGb() float64 {
	if x != nil {
		return x.SizeGb
	}
	return 0
}

type MinDiskArr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Disks         []*MinDisk             `protobuf:"bytes,1,rep,name=disks,proto3" json:"disks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MinDiskArr) Reset() {
	*x = MinDiskArr{}
	mi := &file_btrfs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MinDiskArr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MinDiskArr) ProtoMessage() {}

func (x *MinDiskArr) ProtoReflect() protoreflect.Message {
	mi := &file_btrfs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MinDiskArr.ProtoReflect.Descriptor instead.
func (*MinDiskArr) Descriptor() ([]byte, []int) {
	return file_btrfs_proto_rawDescGZIP(), []int{1}
}

func (x *MinDiskArr) GetDisks() []*MinDisk {
	if x != nil {
		return x.Disks
	}
	return nil
}

type BtrfsDevice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Label         string                 `protobuf:"bytes,4,opt,name=label,proto3" json:"label,omitempty"`
	Uuid          string                 `protobuf:"bytes,5,opt,name=uuid,proto3" json:"uuid,omitempty"`
	UuidSub       string                 `protobuf:"bytes,6,opt,name=uuid_sub,json=uuidSub,proto3" json:"uuid_sub,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,7,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	MountPoint    string                 `protobuf:"bytes,8,opt,name=mount_point,json=mountPoint,proto3" json:"mount_point,omitempty"`
	Mounted       bool                   `protobuf:"varint,9,opt,name=mounted,proto3" json:"mounted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BtrfsDevice) Reset() {
	*x = BtrfsDevice{}
	mi := &file_btrfs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BtrfsDevice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BtrfsDevice) ProtoMessage() {}

func (x *BtrfsDevice) ProtoReflect() protoreflect.Message {
	mi := &file_btrfs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BtrfsDevice.ProtoReflect.Descriptor instead.
func (*BtrfsDevice) Descriptor() ([]byte, []int) {
	return file_btrfs_proto_rawDescGZIP(), []int{2}
}

func (x *BtrfsDevice) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BtrfsDevice) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *BtrfsDevice) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *BtrfsDevice) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *BtrfsDevice) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *BtrfsDevice) GetUuidSub() string {
	if x != nil {
		return x.UuidSub
	}
	return ""
}

func (x *BtrfsDevice) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *BtrfsDevice) GetMountPoint() string {
	if x != nil {
		return x.MountPoint
	}
	return ""
}

func (x *BtrfsDevice) GetMounted() bool {
	if x != nil {
		return x.Mounted
	}
	return false
}

type FileSystem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	FsType        string                 `protobuf:"bytes,3,opt,name=fs_type,json=fsType,proto3" json:"fs_type,omitempty"`
	Options       string                 `protobuf:"bytes,4,opt,name=options,proto3" json:"options,omitempty"`
	Uuid          string                 `protobuf:"bytes,5,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Label         string                 `protobuf:"bytes,6,opt,name=label,proto3" json:"label,omitempty"`
	Compression   string                 `protobuf:"bytes,7,opt,name=compression,proto3" json:"compression,omitempty"`
	MaxSpace      int64                  `protobuf:"varint,8,opt,name=max_space,json=maxSpace,proto3" json:"max_space,omitempty"`
	UsedSpace     int64                  `protobuf:"varint,9,opt,name=used_space,json=usedSpace,proto3" json:"used_space,omitempty"`
	RealMaxSpace  int64                  `protobuf:"varint,10,opt,name=real_max_space,json=realMaxSpace,proto3" json:"real_max_space,omitempty"`
	RealUsedSpace int64                  `protobuf:"varint,11,opt,name=real_used_space,json=realUsedSpace,proto3" json:"real_used_space,omitempty"`
	Devices       []*BtrfsDevice         `protobuf:"bytes,12,rep,name=devices,proto3" json:"devices,omitempty"`
	Children      []*FileSystem          `protobuf:"bytes,13,rep,name=children,proto3" json:"children,omitempty"`
	Mounted       bool                   `protobuf:"varint,14,opt,name=mounted,proto3" json:"mounted,omitempty"`
	RaidType      string                 `protobuf:"bytes,15,opt,name=raid_type,json=raidType,proto3" json:"raid_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileSystem) Reset() {
	*x = FileSystem{}
	mi := &file_btrfs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileSystem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileSystem) ProtoMessage() {}

func (x *FileSystem) ProtoReflect() protoreflect.Message {
	mi := &file_btrfs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileSystem.ProtoReflect.Descriptor instead.
func (*FileSystem) Descriptor() ([]byte, []int) {
	return file_btrfs_proto_rawDescGZIP(), []int{3}
}

func (x *FileSystem) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *FileSystem) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *FileSystem) GetFsType() string {
	if x != nil {
		return x.FsType
	}
	return ""
}

func (x *FileSystem) GetOptions() string {
	if x != nil {
		return x.Options
	}
	return ""
}

func (x *FileSystem) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *FileSystem) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *FileSystem) GetCompression() string {
	if x != nil {
		return x.Compression
	}
	return ""
}

func (x *FileSystem) GetMaxSpace() int64 {
	if x != nil {
		return x.MaxSpace
	}
	return 0
}

func (x *FileSystem) GetUsedSpace() int64 {
	if x != nil {
		return x.UsedSpace
	}
	return 0
}

func (x *FileSystem) GetRealMaxSpace() int64 {
	if x != nil {
		return x.RealMaxSpace
	}
	return 0
}

func (x *FileSystem) GetRealUsedSpace() int64 {
	if x != nil {
		return x.RealUsedSpace
	}
	return 0
}

func (x *FileSystem) GetDevices() []*BtrfsDevice {
	if x != nil {
		return x.Devices
	}
	return nil
}

func (x *FileSystem) GetChildren() []*FileSystem {
	if x != nil {
		return x.Children
	}
	return nil
}

func (x *FileSystem) GetMounted() bool {
	if x != nil {
		return x.Mounted
	}
	return false
}

func (x *FileSystem) GetRaidType() string {
	if x != nil {
		return x.RaidType
	}
	return ""
}

type FindMntOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filesystems   []*FileSystem          `protobuf:"bytes,1,rep,name=filesystems,proto3" json:"filesystems,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindMntOutput) Reset() {
	*x = FindMntOutput{}
	mi := &file_btrfs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindMntOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindMntOutput) ProtoMessage() {}

func (x *FindMntOutput) ProtoReflect() protoreflect.Message {
	mi := &file_btrfs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindMntOutput.ProtoReflect.Descriptor instead.
func (*FindMntOutput) Descriptor() ([]byte, []int) {
	return file_btrfs_proto_rawDescGZIP(), []int{4}
}

func (x *FindMntOutput) GetFilesystems() []*FileSystem {
	if x != nil {
		return x.Filesystems
	}
	return nil
}

type CreateRaidReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Raid          string                 `protobuf:"bytes,2,opt,name=raid,proto3" json:"raid,omitempty"`
	Disks         []string               `protobuf:"bytes,3,rep,name=disks,proto3" json:"disks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRaidReq) Reset() {
	*x = CreateRaidReq{}
	mi := &file_btrfs_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRaidReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRaidReq) ProtoMessage() {}

func (x *CreateRaidReq) ProtoReflect() protoreflect.Message {
	mi := &file_btrfs_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRaidReq.ProtoReflect.Descriptor instead.
func (*CreateRaidReq) Descriptor() ([]byte, []int) {
	return file_btrfs_proto_rawDescGZIP(), []int{5}
}

func (x *CreateRaidReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRaidReq) GetRaid() string {
	if x != nil {
		return x.Raid
	}
	return ""
}

func (x *CreateRaidReq) GetDisks() []string {
	if x != nil {
		return x.Disks
	}
	return nil
}

type UUIDReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UUIDReq) Reset() {
	*x = UUIDReq{}
	mi := &file_btrfs_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UUIDReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UUIDReq) ProtoMessage() {}

func (x *UUIDReq) ProtoReflect() protoreflect.Message {
	mi := &file_btrfs_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UUIDReq.ProtoReflect.Descriptor instead.
func (*UUIDReq) Descriptor() ([]byte, []int) {
	return file_btrfs_proto_rawDescGZIP(), []int{6}
}

func (x *UUIDReq) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type MountReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Compression   string                 `protobuf:"bytes,3,opt,name=compression,proto3" json:"compression,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MountReq) Reset() {
	*x = MountReq{}
	mi := &file_btrfs_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MountReq) ProtoMessage() {}

func (x *MountReq) ProtoReflect() protoreflect.Message {
	mi := &file_btrfs_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MountReq.ProtoReflect.Descriptor instead.
func (*MountReq) Descriptor() ([]byte, []int) {
	return file_btrfs_proto_rawDescGZIP(), []int{7}
}

func (x *MountReq) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *MountReq) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *MountReq) GetCompression() string {
	if x != nil {
		return x.Compression
	}
	return ""
}

type UMountReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Force         bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UMountReq) Reset() {
	*x = UMountReq{}
	mi := &file_btrfs_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UMountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UMountReq) ProtoMessage() {}

func (x *UMountReq) ProtoReflect() protoreflect.Message {
	mi := &file_btrfs_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UMountReq.ProtoReflect.Descriptor instead.
func (*UMountReq) Descriptor() ([]byte, []int) {
	return file_btrfs_proto_rawDescGZIP(), []int{8}
}

func (x *UMountReq) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *UMountReq) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type AddDiskToRaidReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	DiskPath      string                 `protobuf:"bytes,2,opt,name=diskPath,proto3" json:"diskPath,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddDiskToRaidReq) Reset() {
	*x = AddDiskToRaidReq{}
	mi := &file_btrfs_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddDiskToRaidReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDiskToRaidReq) ProtoMessage() {}

func (x *AddDiskToRaidReq) ProtoReflect() protoreflect.Message {
	mi := &file_btrfs_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDiskToRaidReq.ProtoReflect.Descriptor instead.
func (*AddDiskToRaidReq) Descriptor() ([]byte, []int) {
	return file_btrfs_proto_rawDescGZIP(), []int{9}
}

func (x *AddDiskToRaidReq) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *AddDiskToRaidReq) GetDiskPath() string {
	if x != nil {
		return x.DiskPath
	}
	return ""
}

type RemoveDiskFromRaidReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	DiskPath      string                 `protobuf:"bytes,2,opt,name=diskPath,proto3" json:"diskPath,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveDiskFromRaidReq) Reset() {
	*x = RemoveDiskFromRaidReq{}
	mi := &file_btrfs_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveDiskFromRaidReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveDiskFromRaidReq) ProtoMessage() {}

func (x *RemoveDiskFromRaidReq) ProtoReflect() protoreflect.Message {
	mi := &file_btrfs_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveDiskFromRaidReq.ProtoReflect.Descriptor instead.
func (*RemoveDiskFromRaidReq) Descriptor() ([]byte, []int) {
	return file_btrfs_proto_rawDescGZIP(), []int{10}
}

func (x *RemoveDiskFromRaidReq) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *RemoveDiskFromRaidReq) GetDiskPath() string {
	if x != nil {
		return x.DiskPath
	}
	return ""
}

type ReplaceDiskToRaidReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	OldDiskPath   string                 `protobuf:"bytes,2,opt,name=oldDiskPath,proto3" json:"oldDiskPath,omitempty"`
	NewDiskPath   string                 `protobuf:"bytes,3,opt,name=newDiskPath,proto3" json:"newDiskPath,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplaceDiskToRaidReq) Reset() {
	*x = ReplaceDiskToRaidReq{}
	mi := &file_btrfs_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplaceDiskToRaidReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplaceDiskToRaidReq) ProtoMessage() {}

func (x *ReplaceDiskToRaidReq) ProtoReflect() protoreflect.Message {
	mi := &file_btrfs_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplaceDiskToRaidReq.ProtoReflect.Descriptor instead.
func (*ReplaceDiskToRaidReq) Descriptor() ([]byte, []int) {
	return file_btrfs_proto_rawDescGZIP(), []int{11}
}

func (x *ReplaceDiskToRaidReq) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *ReplaceDiskToRaidReq) GetOldDiskPath() string {
	if x != nil {
		return x.OldDiskPath
	}
	return ""
}

func (x *ReplaceDiskToRaidReq) GetNewDiskPath() string {
	if x != nil {
		return x.NewDiskPath
	}
	return ""
}

type ChangeRaidLevelReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	RaidType      string                 `protobuf:"bytes,2,opt,name=raidType,proto3" json:"raidType,omitempty"`
	BalanceStatus string                 `protobuf:"bytes,8,opt,name=balance_status,json=balanceStatus,proto3" json:"balance_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeRaidLevelReq) Reset() {
	*x = ChangeRaidLevelReq{}
	mi := &file_btrfs_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeRaidLevelReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeRaidLevelReq) ProtoMessage() {}

func (x *ChangeRaidLevelReq) ProtoReflect() protoreflect.Message {
	mi := &file_btrfs_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeRaidLevelReq.ProtoReflect.Descriptor instead.
func (*ChangeRaidLevelReq) Descriptor() ([]byte, []int) {
	return file_btrfs_proto_rawDescGZIP(), []int{12}
}

func (x *ChangeRaidLevelReq) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *ChangeRaidLevelReq) GetRaidType() string {
	if x != nil {
		return x.RaidType
	}
	return ""
}

func (x *ChangeRaidLevelReq) GetBalanceStatus() string {
	if x != nil {
		return x.BalanceStatus
	}
	return ""
}

type DeviceStat struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Device         string                 `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	DevId          int32                  `protobuf:"varint,2,opt,name=dev_id,json=devId,proto3" json:"dev_id,omitempty"`
	WriteIoErrs    int32                  `protobuf:"varint,3,opt,name=write_io_errs,json=writeIoErrs,proto3" json:"write_io_errs,omitempty"`
	ReadIoErrs     int32                  `protobuf:"varint,4,opt,name=read_io_errs,json=readIoErrs,proto3" json:"read_io_errs,omitempty"`
	FlushIoErrs    int32                  `protobuf:"varint,5,opt,name=flush_io_errs,json=flushIoErrs,proto3" json:"flush_io_errs,omitempty"`
	CorruptionErrs int32                  `protobuf:"varint,6,opt,name=corruption_errs,json=corruptionErrs,proto3" json:"corruption_errs,omitempty"`
	GenerationErrs int32                  `protobuf:"varint,7,opt,name=generation_errs,json=generationErrs,proto3" json:"generation_errs,omitempty"`
	BalanceStatus  string                 `protobuf:"bytes,8,opt,name=balanceStatus,proto3" json:"balanceStatus,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeviceStat) Reset() {
	*x = DeviceStat{}
	mi := &file_btrfs_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceStat) ProtoMessage() {}

func (x *DeviceStat) ProtoReflect() protoreflect.Message {
	mi := &file_btrfs_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceStat.ProtoReflect.Descriptor instead.
func (*DeviceStat) Descriptor() ([]byte, []int) {
	return file_btrfs_proto_rawDescGZIP(), []int{13}
}

func (x *DeviceStat) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *DeviceStat) GetDevId() int32 {
	if x != nil {
		return x.DevId
	}
	return 0
}

func (x *DeviceStat) GetWriteIoErrs() int32 {
	if x != nil {
		return x.WriteIoErrs
	}
	return 0
}

func (x *DeviceStat) GetReadIoErrs() int32 {
	if x != nil {
		return x.ReadIoErrs
	}
	return 0
}

func (x *DeviceStat) GetFlushIoErrs() int32 {
	if x != nil {
		return x.FlushIoErrs
	}
	return 0
}

func (x *DeviceStat) GetCorruptionErrs() int32 {
	if x != nil {
		return x.CorruptionErrs
	}
	return 0
}

func (x *DeviceStat) GetGenerationErrs() int32 {
	if x != nil {
		return x.GenerationErrs
	}
	return 0
}

func (x *DeviceStat) GetBalanceStatus() string {
	if x != nil {
		return x.BalanceStatus
	}
	return ""
}

type RaidStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	DeviceStats   []*DeviceStat          `protobuf:"bytes,2,rep,name=device_stats,json=deviceStats,proto3" json:"device_stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaidStats) Reset() {
	*x = RaidStats{}
	mi := &file_btrfs_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaidStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaidStats) ProtoMessage() {}

func (x *RaidStats) ProtoReflect() protoreflect.Message {
	mi := &file_btrfs_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaidStats.ProtoReflect.Descriptor instead.
func (*RaidStats) Descriptor() ([]byte, []int) {
	return file_btrfs_proto_rawDescGZIP(), []int{14}
}

func (x *RaidStats) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RaidStats) GetDeviceStats() []*DeviceStat {
	if x != nil {
		return x.DeviceStats
	}
	return nil
}

type ScrubStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	StartedAt     string                 `protobuf:"bytes,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	Duration      string                 `protobuf:"bytes,5,opt,name=duration,proto3" json:"duration,omitempty"`
	TimeLeft      string                 `protobuf:"bytes,6,opt,name=time_left,json=timeLeft,proto3" json:"time_left,omitempty"`
	TotalToScrub  string                 `protobuf:"bytes,7,opt,name=total_to_scrub,json=totalToScrub,proto3" json:"total_to_scrub,omitempty"`
	BytesScrubbed string                 `protobuf:"bytes,8,opt,name=bytes_scrubbed,json=bytesScrubbed,proto3" json:"bytes_scrubbed,omitempty"`
	Rate          string                 `protobuf:"bytes,9,opt,name=rate,proto3" json:"rate,omitempty"`
	ErrorSummary  string                 `protobuf:"bytes,10,opt,name=error_summary,json=errorSummary,proto3" json:"error_summary,omitempty"`
	PercentDone   float64                `protobuf:"fixed64,11,opt,name=percent_done,json=percentDone,proto3" json:"percent_done,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScrubStatus) Reset() {
	*x = ScrubStatus{}
	mi := &file_btrfs_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScrubStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScrubStatus) ProtoMessage() {}

func (x *ScrubStatus) ProtoReflect() protoreflect.Message {
	mi := &file_btrfs_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScrubStatus.ProtoReflect.Descriptor instead.
func (*ScrubStatus) Descriptor() ([]byte, []int) {
	return file_btrfs_proto_rawDescGZIP(), []int{15}
}

func (x *ScrubStatus) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *ScrubStatus) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ScrubStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ScrubStatus) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *ScrubStatus) GetDuration() string {
	if x != nil {
		return x.Duration
	}
	return ""
}

func (x *ScrubStatus) GetTimeLeft() string {
	if x != nil {
		return x.TimeLeft
	}
	return ""
}

func (x *ScrubStatus) GetTotalToScrub() string {
	if x != nil {
		return x.TotalToScrub
	}
	return ""
}

func (x *ScrubStatus) GetBytesScrubbed() string {
	if x != nil {
		return x.BytesScrubbed
	}
	return ""
}

func (x *ScrubStatus) GetRate() string {
	if x != nil {
		return x.Rate
	}
	return ""
}

func (x *ScrubStatus) GetErrorSummary() string {
	if x != nil {
		return x.ErrorSummary
	}
	return ""
}

func (x *ScrubStatus) GetPercentDone() float64 {
	if x != nil {
		return x.PercentDone
	}
	return 0
}

type MountRaidRet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Degraded      bool                   `protobuf:"varint,1,opt,name=degraded,proto3" json:"degraded,omitempty"`
	Problems      []string               `protobuf:"bytes,2,rep,name=Problems,proto3" json:"Problems,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MountRaidRet) Reset() {
	*x = MountRaidRet{}
	mi := &file_btrfs_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MountRaidRet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MountRaidRet) ProtoMessage() {}

func (x *MountRaidRet) ProtoReflect() protoreflect.Message {
	mi := &file_btrfs_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MountRaidRet.ProtoReflect.Descriptor instead.
func (*MountRaidRet) Descriptor() ([]byte, []int) {
	return file_btrfs_proto_rawDescGZIP(), []int{16}
}

func (x *MountRaidRet) GetDegraded() bool {
	if x != nil {
		return x.Degraded
	}
	return false
}

func (x *MountRaidRet) GetProblems() []string {
	if x != nil {
		return x.Problems
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_btrfs_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_btrfs_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_btrfs_proto_rawDescGZIP(), []int{17}
}

var File_btrfs_proto protoreflect.FileDescriptor

const file_btrfs_proto_rawDesc = "" +
	"\n" +
	"\vbtrfs.proto\x12\x05btrfs\"P\n" +
	"\aMinDisk\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\amounted\x18\x02 \x01(\bR\amounted\x12\x17\n" +
	"\asize_gb\x18\x03 \x01(\x01R\x06sizeGb\"2\n" +
	"\n" +
	"MinDiskArr\x12$\n" +
	"\x05disks\x18\x01 \x03(\v2\x0e.btrfs.MinDiskR\x05disks\"\xe8\x01\n" +
	"\vBtrfsDevice\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x14\n" +
	"\x05label\x18\x04 \x01(\tR\x05label\x12\x12\n" +
	"\x04uuid\x18\x05 \x01(\tR\x04uuid\x12\x19\n" +
	"\buuid_sub\x18\x06 \x01(\tR\auuidSub\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\a \x01(\x03R\tsizeBytes\x12\x1f\n" +
	"\vmount_point\x18\b \x01(\tR\n" +
	"mountPoint\x12\x18\n" +
	"\amounted\x18\t \x01(\bR\amounted\"\xd9\x03\n" +
	"\n" +
	"FileSystem\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x17\n" +
	"\afs_type\x18\x03 \x01(\tR\x06fsType\x12\x18\n" +
	"\aoptions\x18\x04 \x01(\tR\aoptions\x12\x12\n" +
	"\x04uuid\x18\x05 \x01(\tR\x04uuid\x12\x14\n" +
	"\x05label\x18\x06 \x01(\tR\x05label\x12 \n" +
	"\vcompression\x18\a \x01(\tR\vcompression\x12\x1b\n" +
	"\tmax_space\x18\b \x01(\x03R\bmaxSpace\x12\x1d\n" +
	"\n" +
	"used_space\x18\t \x01(\x03R\tusedSpace\x12$\n" +
	"\x0ereal_max_space\x18\n" +
	" \x01(\x03R\frealMaxSpace\x12&\n" +
	"\x0freal_used_space\x18\v \x01(\x03R\rrealUsedSpace\x12,\n" +
	"\adevices\x18\f \x03(\v2\x12.btrfs.BtrfsDeviceR\adevices\x12-\n" +
	"\bchildren\x18\r \x03(\v2\x11.btrfs.FileSystemR\bchildren\x12\x18\n" +
	"\amounted\x18\x0e \x01(\bR\amounted\x12\x1b\n" +
	"\traid_type\x18\x0f \x01(\tR\braidType\"D\n" +
	"\rFindMntOutput\x123\n" +
	"\vfilesystems\x18\x01 \x03(\v2\x11.btrfs.FileSystemR\vfilesystems\"M\n" +
	"\rCreateRaidReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04raid\x18\x02 \x01(\tR\x04raid\x12\x14\n" +
	"\x05disks\x18\x03 \x03(\tR\x05disks\"\x1d\n" +
	"\aUUIDReq\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"X\n" +
	"\bMountReq\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12 \n" +
	"\vcompression\x18\x03 \x01(\tR\vcompression\"5\n" +
	"\tUMountReq\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"B\n" +
	"\x10AddDiskToRaidReq\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x1a\n" +
	"\bdiskPath\x18\x02 \x01(\tR\bdiskPath\"G\n" +
	"\x15RemoveDiskFromRaidReq\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x1a\n" +
	"\bdiskPath\x18\x02 \x01(\tR\bdiskPath\"n\n" +
	"\x14ReplaceDiskToRaidReq\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12 \n" +
	"\voldDiskPath\x18\x02 \x01(\tR\voldDiskPath\x12 \n" +
	"\vnewDiskPath\x18\x03 \x01(\tR\vnewDiskPath\"k\n" +
	"\x12ChangeRaidLevelReq\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x1a\n" +
	"\braidType\x18\x02 \x01(\tR\braidType\x12%\n" +
	"\x0ebalance_status\x18\b \x01(\tR\rbalanceStatus\"\x9d\x02\n" +
	"\n" +
	"DeviceStat\x12\x16\n" +
	"\x06device\x18\x01 \x01(\tR\x06device\x12\x15\n" +
	"\x06dev_id\x18\x02 \x01(\x05R\x05devId\x12\"\n" +
	"\rwrite_io_errs\x18\x03 \x01(\x05R\vwriteIoErrs\x12 \n" +
	"\fread_io_errs\x18\x04 \x01(\x05R\n" +
	"readIoErrs\x12\"\n" +
	"\rflush_io_errs\x18\x05 \x01(\x05R\vflushIoErrs\x12'\n" +
	"\x0fcorruption_errs\x18\x06 \x01(\x05R\x0ecorruptionErrs\x12'\n" +
	"\x0fgeneration_errs\x18\a \x01(\x05R\x0egenerationErrs\x12$\n" +
	"\rbalanceStatus\x18\b \x01(\tR\rbalanceStatus\"[\n" +
	"\tRaidStats\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x124\n" +
	"\fdevice_stats\x18\x02 \x03(\v2\x11.btrfs.DeviceStatR\vdeviceStats\"\xce\x02\n" +
	"\vScrubStatus\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"started_at\x18\x04 \x01(\tR\tstartedAt\x12\x1a\n" +
	"\bduration\x18\x05 \x01(\tR\bduration\x12\x1b\n" +
	"\ttime_left\x18\x06 \x01(\tR\btimeLeft\x12$\n" +
	"\x0etotal_to_scrub\x18\a \x01(\tR\ftotalToScrub\x12%\n" +
	"\x0ebytes_scrubbed\x18\b \x01(\tR\rbytesScrubbed\x12\x12\n" +
	"\x04rate\x18\t \x01(\tR\x04rate\x12#\n" +
	"\rerror_summary\x18\n" +
	" \x01(\tR\ferrorSummary\x12!\n" +
	"\fpercent_done\x18\v \x01(\x01R\vpercentDone\"F\n" +
	"\fMountRaidRet\x12\x1a\n" +
	"\bdegraded\x18\x01 \x01(\bR\bdegraded\x12\x1a\n" +
	"\bProblems\x18\x02 \x03(\tR\bProblems\"\a\n" +
	"\x05Empty2\xdb\a\n" +
	"\fBtrFSService\x12.\n" +
	"\vGetAllDisks\x12\f.btrfs.Empty\x1a\x11.btrfs.MinDiskArr\x127\n" +
	"\x11GetAllFileSystems\x12\f.btrfs.Empty\x1a\x14.btrfs.FindMntOutput\x125\n" +
	"\rGetFileSystem\x12\x0e.btrfs.UUIDReq\x1a\x14.btrfs.FindMntOutput\x120\n" +
	"\n" +
	"CreateRaid\x12\x14.btrfs.CreateRaidReq\x1a\f.btrfs.Empty\x12*\n" +
	"\n" +
	"RemoveRaid\x12\x0e.btrfs.UUIDReq\x1a\f.btrfs.Empty\x121\n" +
	"\tMountRaid\x12\x0f.btrfs.MountReq\x1a\x13.btrfs.MountRaidRet\x12,\n" +
	"\n" +
	"UMountRaid\x12\x10.btrfs.UMountReq\x1a\f.btrfs.Empty\x126\n" +
	"\rAddDiskToRaid\x12\x17.btrfs.AddDiskToRaidReq\x1a\f.btrfs.Empty\x12@\n" +
	"\x12RemoveDiskFromRaid\x12\x1c.btrfs.RemoveDiskFromRaidReq\x1a\f.btrfs.Empty\x12>\n" +
	"\x11ReplaceDiskInRaid\x12\x1b.btrfs.ReplaceDiskToRaidReq\x1a\f.btrfs.Empty\x12:\n" +
	"\x0fChangeRaidLevel\x12\x19.btrfs.ChangeRaidLevelReq\x1a\f.btrfs.Empty\x12+\n" +
	"\vBalanceRaid\x12\x0e.btrfs.UUIDReq\x1a\f.btrfs.Empty\x12.\n" +
	"\x0eDefragmentRaid\x12\x0e.btrfs.UUIDReq\x1a\f.btrfs.Empty\x12)\n" +
	"\tScrubRaid\x12\x0e.btrfs.UUIDReq\x1a\f.btrfs.Empty\x120\n" +
	"\fGetRaidStats\x12\x0e.btrfs.UUIDReq\x1a\x10.btrfs.RaidStats\x12,\n" +
	"\fPauseBalance\x12\x0e.btrfs.UUIDReq\x1a\f.btrfs.Empty\x12-\n" +
	"\rResumeBalance\x12\x0e.btrfs.UUIDReq\x1a\f.btrfs.Empty\x12-\n" +
	"\rCancelBalance\x12\x0e.btrfs.UUIDReq\x1a\f.btrfs.Empty\x120\n" +
	"\n" +
	"ScrubStats\x12\x0e.btrfs.UUIDReq\x1a\x12.btrfs.ScrubStatusB3Z1github.com/Maruqes/512SvMan/api/proto/btrfs;protob\x06proto3"

var (
	file_btrfs_proto_rawDescOnce sync.Once
	file_btrfs_proto_rawDescData []byte
)

func file_btrfs_proto_rawDescGZIP() []byte {
	file_btrfs_proto_rawDescOnce.Do(func() {
		file_btrfs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_btrfs_proto_rawDesc), len(file_btrfs_proto_rawDesc)))
	})
	return file_btrfs_proto_rawDescData
}

var file_btrfs_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_btrfs_proto_goTypes = []any{
	(*MinDisk)(nil),               // 0: btrfs.MinDisk
	(*MinDiskArr)(nil),            // 1: btrfs.MinDiskArr
	(*BtrfsDevice)(nil),           // 2: btrfs.BtrfsDevice
	(*FileSystem)(nil),            // 3: btrfs.FileSystem
	(*FindMntOutput)(nil),         // 4: btrfs.FindMntOutput
	(*CreateRaidReq)(nil),         // 5: btrfs.CreateRaidReq
	(*UUIDReq)(nil),               // 6: btrfs.UUIDReq
	(*MountReq)(nil),              // 7: btrfs.MountReq
	(*UMountReq)(nil),             // 8: btrfs.UMountReq
	(*AddDiskToRaidReq)(nil),      // 9: btrfs.AddDiskToRaidReq
	(*RemoveDiskFromRaidReq)(nil), // 10: btrfs.RemoveDiskFromRaidReq
	(*ReplaceDiskToRaidReq)(nil),  // 11: btrfs.ReplaceDiskToRaidReq
	(*ChangeRaidLevelReq)(nil),    // 12: btrfs.ChangeRaidLevelReq
	(*DeviceStat)(nil),            // 13: btrfs.DeviceStat
	(*RaidStats)(nil),             // 14: btrfs.RaidStats
	(*ScrubStatus)(nil),           // 15: btrfs.ScrubStatus
	(*MountRaidRet)(nil),          // 16: btrfs.MountRaidRet
	(*Empty)(nil),                 // 17: btrfs.Empty
}
var file_btrfs_proto_depIdxs = []int32{
	0,  // 0: btrfs.MinDiskArr.disks:type_name -> btrfs.MinDisk
	2,  // 1: btrfs.FileSystem.devices:type_name -> btrfs.BtrfsDevice
	3,  // 2: btrfs.FileSystem.children:type_name -> btrfs.FileSystem
	3,  // 3: btrfs.FindMntOutput.filesystems:type_name -> btrfs.FileSystem
	13, // 4: btrfs.RaidStats.device_stats:type_name -> btrfs.DeviceStat
	17, // 5: btrfs.BtrFSService.GetAllDisks:input_type -> btrfs.Empty
	17, // 6: btrfs.BtrFSService.GetAllFileSystems:input_type -> btrfs.Empty
	6,  // 7: btrfs.BtrFSService.GetFileSystem:input_type -> btrfs.UUIDReq
	5,  // 8: btrfs.BtrFSService.CreateRaid:input_type -> btrfs.CreateRaidReq
	6,  // 9: btrfs.BtrFSService.RemoveRaid:input_type -> btrfs.UUIDReq
	7,  // 10: btrfs.BtrFSService.MountRaid:input_type -> btrfs.MountReq
	8,  // 11: btrfs.BtrFSService.UMountRaid:input_type -> btrfs.UMountReq
	9,  // 12: btrfs.BtrFSService.AddDiskToRaid:input_type -> btrfs.AddDiskToRaidReq
	10, // 13: btrfs.BtrFSService.RemoveDiskFromRaid:input_type -> btrfs.RemoveDiskFromRaidReq
	11, // 14: btrfs.BtrFSService.ReplaceDiskInRaid:input_type -> btrfs.ReplaceDiskToRaidReq
	12, // 15: btrfs.BtrFSService.ChangeRaidLevel:input_type -> btrfs.ChangeRaidLevelReq
	6,  // 16: btrfs.BtrFSService.BalanceRaid:input_type -> btrfs.UUIDReq
	6,  // 17: btrfs.BtrFSService.DefragmentRaid:input_type -> btrfs.UUIDReq
	6,  // 18: btrfs.BtrFSService.ScrubRaid:input_type -> btrfs.UUIDReq
	6,  // 19: btrfs.BtrFSService.GetRaidStats:input_type -> btrfs.UUIDReq
	6,  // 20: btrfs.BtrFSService.PauseBalance:input_type -> btrfs.UUIDReq
	6,  // 21: btrfs.BtrFSService.ResumeBalance:input_type -> btrfs.UUIDReq
	6,  // 22: btrfs.BtrFSService.CancelBalance:input_type -> btrfs.UUIDReq
	6,  // 23: btrfs.BtrFSService.ScrubStats:input_type -> btrfs.UUIDReq
	1,  // 24: btrfs.BtrFSService.GetAllDisks:output_type -> btrfs.MinDiskArr
	4,  // 25: btrfs.BtrFSService.GetAllFileSystems:output_type -> btrfs.FindMntOutput
	4,  // 26: btrfs.BtrFSService.GetFileSystem:output_type -> btrfs.FindMntOutput
	17, // 27: btrfs.BtrFSService.CreateRaid:output_type -> btrfs.Empty
	17, // 28: btrfs.BtrFSService.RemoveRaid:output_type -> btrfs.Empty
	16, // 29: btrfs.BtrFSService.MountRaid:output_type -> btrfs.MountRaidRet
	17, // 30: btrfs.BtrFSService.UMountRaid:output_type -> btrfs.Empty
	17, // 31: btrfs.BtrFSService.AddDiskToRaid:output_type -> btrfs.Empty
	17, // 32: btrfs.BtrFSService.RemoveDiskFromRaid:output_type -> btrfs.Empty
	17, // 33: btrfs.BtrFSService.ReplaceDiskInRaid:output_type -> btrfs.Empty
	17, // 34: btrfs.BtrFSService.ChangeRaidLevel:output_type -> btrfs.Empty
	17, // 35: btrfs.BtrFSService.BalanceRaid:output_type -> btrfs.Empty
	17, // 36: btrfs.BtrFSService.DefragmentRaid:output_type -> btrfs.Empty
	17, // 37: btrfs.BtrFSService.ScrubRaid:output_type -> btrfs.Empty
	14, // 38: btrfs.BtrFSService.GetRaidStats:output_type -> btrfs.RaidStats
	17, // 39: btrfs.BtrFSService.PauseBalance:output_type -> btrfs.Empty
	17, // 40: btrfs.BtrFSService.ResumeBalance:output_type -> btrfs.Empty
	17, // 41: btrfs.BtrFSService.CancelBalance:output_type -> btrfs.Empty
	15, // 42: btrfs.BtrFSService.ScrubStats:output_type -> btrfs.ScrubStatus
	24, // [24:43] is the sub-list for method output_type
	5,  // [5:24] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_btrfs_proto_init() }
func file_btrfs_proto_init() {
	if File_btrfs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_btrfs_proto_rawDesc), len(file_btrfs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_btrfs_proto_goTypes,
		DependencyIndexes: file_btrfs_proto_depIdxs,
		MessageInfos:      file_btrfs_proto_msgTypes,
	}.Build()
	File_btrfs_proto = out.File
	file_btrfs_proto_goTypes = nil
	file_btrfs_proto_depIdxs = nil
}
