// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.19.6
// source: nfs.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// define struct for NFS
type FolderMount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MachineName   string                 `protobuf:"bytes,1,opt,name=machineName,proto3" json:"machineName,omitempty"`
	FolderPath    string                 `protobuf:"bytes,2,opt,name=folderPath,proto3" json:"folderPath,omitempty"` // shared folder
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`         // nfs source (ip:/path)
	Target        string                 `protobuf:"bytes,4,opt,name=target,proto3" json:"target,omitempty"`         // local mount point
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FolderMount) Reset() {
	*x = FolderMount{}
	mi := &file_nfs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FolderMount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FolderMount) ProtoMessage() {}

func (x *FolderMount) ProtoReflect() protoreflect.Message {
	mi := &file_nfs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FolderMount.ProtoReflect.Descriptor instead.
func (*FolderMount) Descriptor() ([]byte, []int) {
	return file_nfs_proto_rawDescGZIP(), []int{0}
}

func (x *FolderMount) GetMachineName() string {
	if x != nil {
		return x.MachineName
	}
	return ""
}

func (x *FolderMount) GetFolderPath() string {
	if x != nil {
		return x.FolderPath
	}
	return ""
}

func (x *FolderMount) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *FolderMount) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

// --- Wrapper for multiple FolderMount entries ---
type FolderMountList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mounts        []*FolderMount         `protobuf:"bytes,1,rep,name=mounts,proto3" json:"mounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FolderMountList) Reset() {
	*x = FolderMountList{}
	mi := &file_nfs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FolderMountList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FolderMountList) ProtoMessage() {}

func (x *FolderMountList) ProtoReflect() protoreflect.Message {
	mi := &file_nfs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FolderMountList.ProtoReflect.Descriptor instead.
func (*FolderMountList) Descriptor() ([]byte, []int) {
	return file_nfs_proto_rawDescGZIP(), []int{1}
}

func (x *FolderMountList) GetMounts() []*FolderMount {
	if x != nil {
		return x.Mounts
	}
	return nil
}

type DownloadIsoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FolderMount   *FolderMount           `protobuf:"bytes,1,opt,name=folderMount,proto3" json:"folderMount,omitempty"`
	IsoUrl        string                 `protobuf:"bytes,2,opt,name=isoUrl,proto3" json:"isoUrl,omitempty"`
	IsoName       string                 `protobuf:"bytes,3,opt,name=isoName,proto3" json:"isoName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadIsoRequest) Reset() {
	*x = DownloadIsoRequest{}
	mi := &file_nfs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadIsoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadIsoRequest) ProtoMessage() {}

func (x *DownloadIsoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nfs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadIsoRequest.ProtoReflect.Descriptor instead.
func (*DownloadIsoRequest) Descriptor() ([]byte, []int) {
	return file_nfs_proto_rawDescGZIP(), []int{2}
}

func (x *DownloadIsoRequest) GetFolderMount() *FolderMount {
	if x != nil {
		return x.FolderMount
	}
	return nil
}

func (x *DownloadIsoRequest) GetIsoUrl() string {
	if x != nil {
		return x.IsoUrl
	}
	return ""
}

func (x *DownloadIsoRequest) GetIsoName() string {
	if x != nil {
		return x.IsoName
	}
	return ""
}

type CreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_nfs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nfs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_nfs_proto_rawDescGZIP(), []int{3}
}

func (x *CreateResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type MountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MountResponse) Reset() {
	*x = MountResponse{}
	mi := &file_nfs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MountResponse) ProtoMessage() {}

func (x *MountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nfs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MountResponse.ProtoReflect.Descriptor instead.
func (*MountResponse) Descriptor() ([]byte, []int) {
	return file_nfs_proto_rawDescGZIP(), []int{4}
}

func (x *MountResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type UnmountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnmountResponse) Reset() {
	*x = UnmountResponse{}
	mi := &file_nfs_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnmountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnmountResponse) ProtoMessage() {}

func (x *UnmountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nfs_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnmountResponse.ProtoReflect.Descriptor instead.
func (*UnmountResponse) Descriptor() ([]byte, []int) {
	return file_nfs_proto_rawDescGZIP(), []int{5}
}

func (x *UnmountResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_nfs_proto protoreflect.FileDescriptor

const file_nfs_proto_rawDesc = "" +
	"\n" +
	"\tnfs.proto\x12\x03nfs\"\x7f\n" +
	"\vFolderMount\x12 \n" +
	"\vmachineName\x18\x01 \x01(\tR\vmachineName\x12\x1e\n" +
	"\n" +
	"folderPath\x18\x02 \x01(\tR\n" +
	"folderPath\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x16\n" +
	"\x06target\x18\x04 \x01(\tR\x06target\";\n" +
	"\x0fFolderMountList\x12(\n" +
	"\x06mounts\x18\x01 \x03(\v2\x10.nfs.FolderMountR\x06mounts\"z\n" +
	"\x12DownloadIsoRequest\x122\n" +
	"\vfolderMount\x18\x01 \x01(\v2\x10.nfs.FolderMountR\vfolderMount\x12\x16\n" +
	"\x06isoUrl\x18\x02 \x01(\tR\x06isoUrl\x12\x18\n" +
	"\aisoName\x18\x03 \x01(\tR\aisoName\" \n" +
	"\x0eCreateResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\x1f\n" +
	"\rMountResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"!\n" +
	"\x0fUnmountResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok2\xf0\x02\n" +
	"\n" +
	"NFSService\x12;\n" +
	"\x12CreateSharedFolder\x12\x10.nfs.FolderMount\x1a\x13.nfs.CreateResponse\x12;\n" +
	"\x12RemoveSharedFolder\x12\x10.nfs.FolderMount\x1a\x13.nfs.CreateResponse\x123\n" +
	"\vMountFolder\x12\x10.nfs.FolderMount\x1a\x12.nfs.MountResponse\x127\n" +
	"\rUnmountFolder\x12\x10.nfs.FolderMount\x1a\x14.nfs.UnmountResponse\x12=\n" +
	"\x10SyncSharedFolder\x12\x14.nfs.FolderMountList\x1a\x13.nfs.CreateResponse\x12;\n" +
	"\vDownloadIso\x12\x17.nfs.DownloadIsoRequest\x1a\x13.nfs.CreateResponseB1Z/github.com/Maruqes/512SvMan/api/proto/nfs;protob\x06proto3"

var (
	file_nfs_proto_rawDescOnce sync.Once
	file_nfs_proto_rawDescData []byte
)

func file_nfs_proto_rawDescGZIP() []byte {
	file_nfs_proto_rawDescOnce.Do(func() {
		file_nfs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nfs_proto_rawDesc), len(file_nfs_proto_rawDesc)))
	})
	return file_nfs_proto_rawDescData
}

var file_nfs_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_nfs_proto_goTypes = []any{
	(*FolderMount)(nil),        // 0: nfs.FolderMount
	(*FolderMountList)(nil),    // 1: nfs.FolderMountList
	(*DownloadIsoRequest)(nil), // 2: nfs.DownloadIsoRequest
	(*CreateResponse)(nil),     // 3: nfs.CreateResponse
	(*MountResponse)(nil),      // 4: nfs.MountResponse
	(*UnmountResponse)(nil),    // 5: nfs.UnmountResponse
}
var file_nfs_proto_depIdxs = []int32{
	0, // 0: nfs.FolderMountList.mounts:type_name -> nfs.FolderMount
	0, // 1: nfs.DownloadIsoRequest.folderMount:type_name -> nfs.FolderMount
	0, // 2: nfs.NFSService.CreateSharedFolder:input_type -> nfs.FolderMount
	0, // 3: nfs.NFSService.RemoveSharedFolder:input_type -> nfs.FolderMount
	0, // 4: nfs.NFSService.MountFolder:input_type -> nfs.FolderMount
	0, // 5: nfs.NFSService.UnmountFolder:input_type -> nfs.FolderMount
	1, // 6: nfs.NFSService.SyncSharedFolder:input_type -> nfs.FolderMountList
	2, // 7: nfs.NFSService.DownloadIso:input_type -> nfs.DownloadIsoRequest
	3, // 8: nfs.NFSService.CreateSharedFolder:output_type -> nfs.CreateResponse
	3, // 9: nfs.NFSService.RemoveSharedFolder:output_type -> nfs.CreateResponse
	4, // 10: nfs.NFSService.MountFolder:output_type -> nfs.MountResponse
	5, // 11: nfs.NFSService.UnmountFolder:output_type -> nfs.UnmountResponse
	3, // 12: nfs.NFSService.SyncSharedFolder:output_type -> nfs.CreateResponse
	3, // 13: nfs.NFSService.DownloadIso:output_type -> nfs.CreateResponse
	8, // [8:14] is the sub-list for method output_type
	2, // [2:8] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_nfs_proto_init() }
func file_nfs_proto_init() {
	if File_nfs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nfs_proto_rawDesc), len(file_nfs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nfs_proto_goTypes,
		DependencyIndexes: file_nfs_proto_depIdxs,
		MessageInfos:      file_nfs_proto_msgTypes,
	}.Build()
	File_nfs_proto = out.File
	file_nfs_proto_goTypes = nil
	file_nfs_proto_depIdxs = nil
}
